### ISSUE TITLE
D-Link DUB H7 black edition working for me

### ISSUE THREAD

**Issue by EssigGuerkchen** [mvp/uhubctl#104]
Hi,
I've done some testing with some hubs that were laying around at my place and for me, the D-LINK DUB H7 in the black housing is working fine.
uhubctl detects it as "smart hub". I build a little Test Kit with one LED between VBUS and GND to confirm that the port can be switched off and with this hub, it is working. I can switch every port of the hub independently. The hardware revision of the Hub is D1. Maybe only this particular version is working.

Current status for hub 1-1.4 [05e3:0608 USB2.0 Hub, USB 2.10, 4 ports]
  Port 1: 0000 off
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
Current status for hub 1-1 [05e3:0608 USB2.0 Hub, USB 2.10, 4 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0507 power highspeed suspend enable connect [05e3:0608 USB2.0 Hub, USB 2.10, 4 ports].

If I connect my Test Kit to this particular port, nothing happens. On all other Ports the LED is shining.

**Comment by mvp** [comment]
Added in 4e18d53
