### ISSUE TITLE
working hub: StarTech ST4200USBM

### ISSUE THREAD

**Issue by joeyh** [mvp/uhubctl#112]
Tested this hub working with uhubctl. 

https://www.startech.com/Cards-Adapters/USB-2/Hub/Mountable-4-Port-Rugged-Industrial-USB-Hub~ST4200USBM

Current status for hub 1-1 [0409:005a, USB 2.00, 4 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power

**Comment by mvp** [comment]
Thanks for report, @joeyh! This hub is added to the list.

**Comment by mfds** [comment]
Doesn't work for me though. How did you test it @joeyh ?

**Comment by mvp** [comment]
@mfds, what exactly does not work? Does `uhubctl` recognize your hub? Does VBUS turn off when you try to power down port? Please post output of `sudo uhubctl`

**Comment by mfds** [comment]
I think it's VBUS. I'm on a Raspberry Pi 4b and this is the output of `sudo uhubctl`:
```
Current status for hub 2 [1d6b:0003 Linux 4.19.97-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 3.00, 4 ports]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 1-1.4 [0409:005a, USB 2.00, 4 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
Current status for hub 1 [1d6b:0002 Linux 4.19.97-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 2.00, 1 ports]
  Port 1: 0503 power highspeed enable connect [2109:3431 USB2.0 Hub, USB 2.10, 4 ports]
```

I have a clock that doesn't turn off. It does if I do this on a Raspberry Pi 3b but, like you mentioned on your README.md, it will turn off every USB port by design.

**Comment by mvp** [comment]
@mfds, did you check vbus off per this FAQ entry https://github.com/mvp/uhubctl#how-do-i-check-if-my-usb-hub-is-supported-by-uhubctl?
I find it surprising that vbus off does not work for you using ST4200USBM.
@joeyh published long article how he was completely turning off USB HDD connected to this hub http://joeyh.name/blog/entry/usb_drives_with_no_phantom_load

**Comment by mfds** [comment]
@mvp yeah, I tried all the steps there. I can see a `Per-port power switching` within the `lsusb -v` output, I have a usb light that doesn't turn off after issuing the "power off" command. I also tried to run it on different ports (even on a raspberry pi 2) but nothing. I wonder if I should avoid powering it with the USB cable. (there's a power connector to the side)

**Comment by mvp** [comment]
Yes, you should always use external power supply for USB hub for your test to be conclusive.
Power control while powering hub off just USB bus power is never guaranteed.

Now, how are you turning off power? Try connecting your USB light to port 1 of StarTech hub, then issue this command:

    sudo uhubctl -l 1-1.4 -p 1 -a 0

You may need to figure out which port number is which, or just use `-p all` to turn off all ports for your hub.

**Comment by mfds** [comment]
yeah, that's pretty much how I tried to turn the power off (and other variants). Finding the port number is easy, it's written on each port. Guess I'll try to buy an external power supply.
