### ISSUE TITLE
IOI U3H415E1

### ISSUE THREAD

**Issue by serjepatoff** [mvp/uhubctl#116]
Not an issue, just a request for addition of IOI U3H415E1 hub to compatibility list. 

Rather interesting externally powered USB 3.0 hub (http://www.ioi.com.tw/products/proddetail_dl.aspx?AppID=1009&CatID=107&HostID=2035&ProdID=1070092).
 
Pros: 
* Both PPPS and full BC 1.2 support, including CDP, DCP, YD/T, Divider-1A,  Divider-2A, and Divider-2.4A for Charge&Sync compatibility with most devices. 
* Rugged industrial design, optional screw-mount USB plug support, high-reliability circuitry. 
* PPPS works in a very reliable manner. I've just tried to power-cycle 10000 times in a script, works perfectly.
* Per-port power state LEDs.

Cons: 
* Rather hard to buy. You cannot find it in local retail stores or ebay/amazon, but order in an old-school B2B manner via emailing to their manager :)
* Price: $75 per 4–port hub w/power adaptor.

**Comment by mvp** [comment]
Added in a9474fe.
