### ISSUE TITLE
Properly removing device from OS prior to switching it off

### ISSUE THREAD

**Issue by matrix200** [mvp/uhubctl#118]
So I finally managed to get the Amazon hub and sure enough it works like charm (the 4 port variety).
My problem is, that the OS appears to be unaware of the removal and throws an error in dmesg a few seconds after removal saying something about IO error and device missing (its a usb to sata enclosure).
How can I properly remove it to avoid that?
I am of course unmounting the drives beforehand, so thats not the problem.

**Comment by mvp** [comment]
This is duplicate for issue #113. Long story short: Linux kernel is aware, but doesn't send proper event. This is Linux only problem, not applicable on other OSes.
