### ISSUE TITLE
Supported hub: Club3D USB 3.0 Dual Display Docking Station

### ISSUE THREAD

**Issue by matthijskooijman** [mvp/uhubctl#122]
Model number: CSV-3242HD
USB ID: 2109:2811
Ports: 4
USB 3.0
https://www.club-3d.com/en/detail/2406/usb_3.0_dual_display_docking_station/

Port #2 and #3 are exposed on the front of the device. Port #1 connects to the internal docking device / port expander, port #4 connects to a secondary hub (see below). Of the external ports, only port #3 supports power toggling (I haven't tested the internal ports #1 and #4). This is the lower USB3 port on the front. When switching the power off, the green light on the dock also turns off.

This docking station contains a second hub (1a40:0101 Terminus Technology Inc. Hub) that is connected to port 4 of the primary hub. This secondary hub has four ports, available on the back of the device.

I noticed that power switching only works when the hub is  connected to an USB2 port on the PC, when connecting to an USB3 port (with an USB2 cable), the power simply stays on (though IIRC the light does switch off).

**Comment by mvp** [comment]
Thanks for the report, @matthijskooijman ! Added in a2b369559566fa72b44ff73511a4fc74a1ad1c85.

**Comment by matthijskooijman** [comment]
Great! (It's a65c576ca3f though, you linked the wrong commit :-p)
