### ISSUE TITLE
does not respect the CPPFLAGS environment variable

### ISSUE THREAD

**Issue by pabs3** [mvp/uhubctl#125]
The Debian buildd log scanner detects that uhubctl does not respect the CPPFLAGS environment variable for the C pre-processor (cpp):

https://qa.debian.org/bls/packages/u/uhubctl.html
https://qa.debian.org/bls/bytag/W-dpkg-buildflags-missing.html

This particular check is detected by the build log hardening check tool:

https://ruderich.org/simon/blhc/

**Comment by mvp** [comment]
Why should it respect CPPFLAGS? It's not C++ program.

**Comment by mvp** [comment]
Should be fixed in 069c67c.
