### ISSUE TITLE
toggle?

### ISSUE THREAD

**Issue by mxmilkiib** [mvp/uhubctl#130]
I'm turning on and off a USB port with a light in it.

`uhubctl -l 2-1.2.1 -p 2 -a cycle` either turns it on (if it was off) or turns it off then on again after two seconds.

Is there a method of getting a true toggle mode? I.e. when off, `uhubctl -l 2-1.2.1 -p 2 -a toggle` turns it on, and when on `uhubctl -l 2-1.2.1 -p 2 -a toggle` turns it off?

**Comment by mvp** [comment]
Thanks for filing this feature request.
I will think how to add it, but no promises when.

**Comment by Piskvor** [comment]
This is possible to hack around by parsing the output...

`if [ "$(uhubctl -l 1-1.3 -p 4 | grep -cF ' off')" -eq 1 ]; then
    # port is off, enable
	uhubctl -l 1-1.3 -p 4 -a 1
else
    # port is on (or hub not connected), disable
	uhubctl -l 1-1.3 -p 4 -a 0
fi`

**Comment by mvp** [comment]
I looked at this again, and it is proving not worth a trouble - too much code refactoring for little value.
Anyone who needs it (like 2 people in the world including you @mxmilkiib) can easily do it using wrapper like @Piskvor suggested.
Closing...
