### ISSUE TITLE
Show device names in list

### ISSUE THREAD

**Issue by allanlaal** [mvp/uhubctl#131]
`
Current status for hub 1-1 [8087:8000, USB 2.00, 8 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
  Port 5: 0100 power
  Port 6: 0100 power
  Port 7: 0100 power
  Port 8: 0100 power
`

there is no way to distinguish what device is behind what port (what corresponds to the output of lsusb)

**Comment by mvp** [comment]
Device names are already shown in brackets if they are attached to USB port. If nothing attached, you will see just current power state. Try connecting some devices and run uhubctl again.
