### ISSUE TITLE
Rpi  2 B with UH700(UN)

### ISSUE THREAD

**Issue by ruthene** [mvp/uhubctl#133]
Hello,
I'll try to power off one port to UH700(UN) from rpi 2b with this command:
sudo ./uhubctl -a off -p 3 -l 1-1.5.1
The power hub led port down and data is cut.
But I have still power ON at this port.
Could you tell me if my command is it ok?
are they problem?
thanks

**Comment by mvp** [comment]
Ugh. Perhaps this hub (or this particular version) doesn't support vbus turn off - manufacturer saved few cents on circuitry... RPi onboard hub definitely supports it, but it will turn off all ports at once...

**Comment by ruthene** [comment]
For the rpi, I know. I had tested.
But, I need the other ports. It is for that I took this one because it appears in the list and that a member said that it was OK.
The command is it OK?
So It's like very difficult to find a good model. It's very very very random.

**Comment by mvp** [comment]
Most devices reported to compatibility list by other users. I own just a few of them, e.g. D-Link DUBH7, and know that they definitely work properly. We need more input from community to collect information about hubs that actually work properly...

**Comment by ruthene** [comment]
Yes but look at => https://github.com/mvp/uhubctl/issues/129

**Comment by mvp** [comment]
@ruthene, it is possible that your hub is not exactly the same as reported in #129.
We have multiple examples of hubs that have exactly the same model numbers, yet behave differently :(.

Another possibility is that some USB 3 hubs don't work properly in USB 2 mode. All USB 3 hubs must support and advertise themselves as 2 virtual hubs when connected to USB 3 host: USB 3 and USB 2. To turn off power, same physical port must be turned off for both hubs. In your case, you are using your hub in USB 2 mode (because RPi only supports USB 2), and it is possible that this hub has a bug that USB 3 component in it doesn't turn off power in this USB2 case.

**Comment by mvp** [comment]
@ruthene, can you try connecting your hub to any host computer with USB3 port (Linux or Mac) using compliant USB3 cable and check if uhubctl can turn off power in native USB3 mode? Thanks!

**Comment by mvp** [comment]
@ruthene, I don't understand you. Whole point of USB 3 test is using native USB 3 connection - USB 3 host, compliant cable and your USB 3 hub. In this case, hub should be detected as 2 virtual devices: one USB 3, and another USB 2. When you try to turn off power on one of these hubs, uhubctl will automatically control power on another, using the same physical port number. My theory is that should work. And, it perhaps doesn't work if hub is connected in USB 2 only mode, as USB 3 component in it is not turned off.

**Comment by ruthene** [comment]
Synthese:

HUB   TP-LINK UH700(UN)
--
Host                                  | Periphycal | uhubctl Work | Led Hub Port USB Work | Data Cut | Power cut
Raspberry P2 B   - USB2    | USB2        | OK                 | OK                                 | OK          | NOK
Raspberry P2 B   - USB2    | USB3        | OK                 | OK                                 | OK          | NOK
Ubuntu Nativ   USB 3        | USB2        | OK                 | OK                                 | OK          | NOK
Ubuntu Nativ   USB 3        | USB3        | OK                 | OK                                 | OK          | NOK

**Comment by mvp** [comment]
Ah, that's unfortunate. I guess we should either remove this hub from supported list, or at least mark it as not supporting vbus cut :(

**Comment by mvp** [comment]
ok, lets remove it from the list then.
