### ISSUE TITLE
Some hub testing - Info

### ISSUE THREAD

**Issue by tiaanmuller** [mvp/uhubctl#135]
Hi

Tested 3 hubs now, all from your list of "working". I plugged in a phone on usb and checked charging.

Amazonbasics 4-port USB 3.0 Hub 

https://www.amazon.com/gp/product/B00DQFGH80/ref=ppx_yo_dt_b_asin_title_o00__o00_s00?ie=UTF8&psc=1

Worked fine, picked up all 4 ports and could power cycle the port successfully.  Charging stopped when port was switched.

```Current status for hub 20-11 [2109:8110 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 20-2 [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0503 power highspeed enable connect [04e8:6860 SAMSUNG SAMSUNG_Android 1015fa59c10a3905]
```

after power off of port 4

```Current status for hub 20-11 [2109:8110 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
  Port 4: 02a0 power 5gbps Rx.Detect
Sent power off request
New status for hub 20-11 [2109:8110 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
  Port 4: 0080 off
Current status for hub 20-2 [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 4: 0503 power highspeed enable connect [04e8:6860 SAMSUNG SAMSUNG_Android 1015fa59c10a3905]
Sent power off request
New status for hub 20-2 [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 4: 0000 off

Current status for hub 20-11 [2109:8110 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
  Port 4: 0080 off
Sent power on request
New status for hub 20-11 [2109:8110 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 20-2 [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 4: 0000 off
Sent power on request
New status for hub 20-2 [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 4: 0100 power
```

turning off stopped charging and turning on started it again, so I can happily confirm this one works well.

Amazonbasics 7-port USB 3.0 Hub

https://www.amazon.com/gp/product/B00E6GX4BG/ref=ppx_yo_dt_b_asin_title_o00__o00_s00?ie=UTF8&psc=1

Again, worked fine, but I had to disable per port as it has multiple hubs onboard so I had to separately disable usb 3.0 and usb 2.0 hubs.  Switched off charging successfully

Port List:

```Current status for hub 20-11.3 [2109:8110 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 20-11 [2109:8110 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 0203 power 5gbps U0 enable connect [2109:8110 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 20-2.3 [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
Current status for hub 20-2 [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0503 power highspeed enable connect [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 4: 0503 power highspeed enable connect [04e8:6860 SAMSUNG SAMSUNG_Android 1015fa59c10a3905]
```

If i turn just port 4 off, i get: 

```$ uhubctl -a off -p 4
Error: changing port state for multiple hubs at once is not supported.
Use -l to limit operation to one hub!```

as expected as it seems to pick up 2x4 port hubs.  Sending to connected hub:

```$ uhubctl -l 20-2 -a off -p 4
Current status for hub 20-11.3 [2109:8110 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
  Port 4: 02a0 power 5gbps Rx.Detect
Sent power off request
New status for hub 20-11.3 [2109:8110 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
  Port 4: 0080 off
Current status for hub 20-2 [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 4: 0503 power highspeed enable connect [04e8:6860 SAMSUNG SAMSUNG_Android 1015fa59c10a3905]
Sent power off request
New status for hub 20-2 [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 4: 0000 off
```

charging still happens

```$ uhubctl -l 20-11 -a off -p 4
Current status for hub 20-11 [2109:8110 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
  Port 4: 02a0 power 5gbps Rx.Detect
Sent power off request
New status for hub 20-11 [2109:8110 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
  Port 4: 0080 off
Current status for hub 20-2.3 [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 4: 0000 off
Sent power off request
New status for hub 20-2.3 [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 4: 0000 off
```

now charging is off

If i turn only 20-11 back on, i get charging again, if i turn 20-2 on, i see phone again.

3.  Transcend 4 Port USB Hub HUB3 (USB 3.0/USB 3.1 Gen 1)

https://www.amazon.com/gp/product/B005D69QD8/ref=ppx_yo_dt_b_asin_title_o00__o00_s00?ie=UTF8&psc=1

I could see per port power settings, and switch on/off but it did NOT switch off the power on the charging.

running status:

```$ uhubctl
Current status for hub 20-11 [8564:4100 Transcend USB3.1 Hub, USB 3.10, 4 ports]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 20-2 [8564:4100 Transcend USB2.1 Hub, USB 2.10, 4 ports]
  Port 1: 0100 power
  Port 2: 0503 power highspeed enable connect [04e8:6860 SAMSUNG SAMSUNG_Android 1015fa59c10a3905]
  Port 3: 0100 power
  Port 4: 0100 power
```

trying to turn off power to port 2:

```$ uhubctl -p 2 -a off
Current status for hub 20-11 [8564:4100 Transcend USB3.1 Hub, USB 3.10, 4 ports]
  Port 2: 02a0 power 5gbps Rx.Detect
Sent power off request
New status for hub 20-11 [8564:4100 Transcend USB3.1 Hub, USB 3.10, 4 ports]
  Port 2: 00a0 off
Current status for hub 20-2 [8564:4100 Transcend USB2.1 Hub, USB 2.10, 4 ports]
  Port 2: 0503 power highspeed enable connect [04e8:6860 SAMSUNG SAMSUNG_Android 1015fa59c10a3905]
Sent power off request
New status for hub 20-2 [8564:4100 Transcend USB2.1 Hub, USB 2.10, 4 ports]
  Port 2: 0000 off
```

status:
```$ uhubctl
Current status for hub 20-11 [8564:4100 Transcend USB3.1 Hub, USB 3.10, 4 ports]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 00a0 off
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 20-2 [8564:4100 Transcend USB2.1 Hub, USB 2.10, 4 ports]
  Port 1: 0100 power
  Port 2: 0000 off
  Port 3: 0100 power
  Port 4: 0100 power
```
however, phone is still charging.  Interestingly enough, i tried the fast charging port too and it couldn't fast charge my Samsung S6.

So it looks like that one doesn't work correctly.   I also tried with the -r 10 parameter.

Here's everything that's on it (beyond the link above)
4  port hub
input DC 12V--2A
kcc-rem-trd-ts-hub3

The box does say at the bottom 84-0470 V2.0 but unsure if that is for packaging or hub itself.

As another observation, it looks like many people go and check whether it can list the power status of the ports and then says it works, but they don't actually try to turn off the power.  I have the same "identifier" for the hub as your listing... [8564:4100 Transcend USB3.1 Hub, USB 3.10, 4 ports] but it clearly isn't working.

oh yes, final note, tested on a Macbook Pro 2014, running Sierra.

Regards
Tiaan

**Comment by mvp** [comment]
Thanks for your report! I'm glad that AmazonBasics hubs are confirmed again to  be a solid choice for USB power control.

7 port hubs are 2x4 port hubs daisy chained internally. In addition to that, we have USB2/3 duality, which means you will see 4 virtual hubs. That makes it rather difficult to understand what's going on. You should always specify hub location (aka address). Also, never try to control port used for daisy chaining - it may confuse internal hub chip and whole hub will start behaving strange.

Also, with so many virtual hubs, it becomes a challenge to detect which hub is dual to which. By default, uhubctl will try to detect dual hubs and control power on them, but unfortunately this algorithm is not bullet proof. You can bypass automatic duality handling using `-e`, but then you need to issue 2 commands to control USB 2 and USB 3 hubs separately. However, in that case, order of control may matter - some hubs need USB 3 turned off first, then USB 2 (or other way around).

As for option `-r N`, it is not needed if there is no device connected to controlled port.

Regarding Transcend hub, perhaps we should remove it from supported list...

**Comment by mvp** [comment]
Removed Transcend TS-HUB3K in 43edb16298315f.
