### ISSUE TITLE
My command turn down multiple port at same time. 

### ISSUE THREAD

**Issue by ejay-ibm** [mvp/uhubctl#141]
hello, 
Can you confirm My understanding of issue #64 . 
I have a Fan usb connected that I want to turn off 
The only way I have been able to make it is with command : 
sudo ./uhubctl -l 1-1 -a off -p 2 
But that turn off as well my wifi card usb connected . 

Does this mean that I can not  ( because of the pi architecture) control my usb power port individually ?  ( btw I don't care about my eth port I don't use it . ) 

pi@ejaypi:~/uhubctl$ sudo ./uhubctl
Current status for hub 1-1.1 [0424:2514, USB 2.00, 3 ports]
  Port 1: 0503 power highspeed enable connect [0424:7800]
  Port 2: 0103 power enable connect [0556:0002 AKM AK5371]
  Port 3: 0100 power
Current status for hub 1-1 [0424:2514, USB 2.00, 4 ports]
  Port 1: 0503 power highspeed enable connect [0424:2514, USB 2.00, 3 ports]
  Port 2: 0100 power
  Port 3: 0503 power highspeed enable connect [0bda:8178 Realtek 802.11n WLAN Adapter 00e04c000001]
  Port 4: 0100 power

Is there any workaround like a particular setup of the usb card to be able to switch only one off and leave the others up ? 

Thank you !

**Comment by mvp** [comment]
Yes, this is indeed dupe for issue #64. It's due Raspberry Pi hardware design - port 1 is wired to control power on onboard wifi+network, and port 2 is wired to control power on all remaining ports 2,3,4,5.

To solve this issue, you can buy any external USB hub from supported list, attach it to Raspberry Pi, and control power on it's ports independently.
