### ISSUE TITLE
toggle script code won't run

### ISSUE THREAD

**Issue by The-Math-God** [mvp/uhubctl#151]
hi i have made a toggle script code with uhubctl  

#!/bin/bash
if /home/pi/uhubctl/uhubctl -l 1-1.1 -p 3; then
   echo off
else
   echo on
fi

but i'm having an issue when i try to run it gives me a command not found error
![command not found](https://user-images.githubusercontent.com/41482138/57252740-ef6efe00-701a-11e9-9203-fca96c8fec1f.JPG)
and the only command that is the problem is in the if section 
but when i run /home/pi/uhubctl/uhubctl -l 1-1.1 -p 3 right on the terminal it returns the status just fine
![worked](https://user-images.githubusercontent.com/41482138/57252661-b46cca80-701a-11e9-8395-ed0cc783d415.JPG)
any ideas?

**Comment by mvp** [comment]
It is hard to tell what is really wrong in your script - I think you only show part of it.

That said, can you install uhubctl as system tool in `/usr/sbin`? That should happen automatically if you do

    git clone https://github.com/mvp/uhubctl
    cd uhubctl
    make install
    sudo make install

Second, it would be really good idea to fix USB permissions as described here: https://github.com/mvp/uhubctl/blob/master/README.md#linux-usb-permissions
After doing it, you would not need to use sudo for uhubctl to work, and it will make your script work more reliably.

Also, if you want to get current port state, I recommend using this snippet:

    uhubctl -l 1-1.1 -p 3 | tail -1 | awk '{print $4}'

It will print `power` if power is on, and `off` is power is off.

**Comment by The-Math-God** [comment]
ok i did manage to find the issue for my previous code but no matter the status it always sent the first echo
now with your new code i can get status prints but i still have the problem but we are very close

heres my updated code
`#!/bin/bash
 if /home/pi/uhubctl/uhubctl -l 1-1.1 -p 3 | tail -1 | cut -f 6 -d " "; then
    echo on
else
    echo off
fi
`

**Comment by mvp** [comment]
Just use this instead:

```
#!/bin/bash
uhubctl -l 1-1.1 -p 3 | tail -1 | cut -f 6 -d " "
```

It will print `power` or `off`.
