### ISSUE TITLE
MOXA UPort 407 Information

### ISSUE THREAD

**Issue by CWZ7605** [mvp/uhubctl#156]
OMG, I forgot to say that, 407 has 7 USB ports, and 404 has 4 USB ports.

But I only have 407, so I do not know whether 404 also support uhubctl.

👍

**Comment by mvp** [comment]
Thanks, I prefer to not add to the table unless it is reported by someone who owns the hardware. E.g. D-Link DUB-H7 rev A works great, but D-Link DUB-H4 rev A does not.

**Comment by CWZ7605** [comment]
I mean 407 has 7 USB ports, so you need to update the information.

**Comment by mvp** [comment]
Ah, good catch! Thanks, will update!

**Comment by mvp** [comment]
Fixed in 94a95a70115651f8cf9884bb7277eb4b58f16d2d.
