### ISSUE TITLE
Add Dell P2416D Internal USB Hub to Compatible List

### ISSUE THREAD

**Issue by fanvinga** [mvp/uhubctl#164]

**Comment by fanvinga** [comment]
I'm using macOS 10.14.5 with latest uhubctl version installed by homebrew.The internal usb hub provided by Dell P2416D works well with uhubctl.

**Comment by fanvinga** [comment]
But i have already sold out my this monitor.So maybe i cannot provide the uhubctl output for further help:(

**Comment by mvp** [comment]
Added in 078f9ee.
