### ISSUE TITLE
Plugable USB2-HUB10C2

### ISSUE THREAD

**Issue by pdh11** [mvp/uhubctl#168]
I couldn't get hold of a Plugable USB2-HUB10S as listed on the compatibility page, so (on the basis that several other Plugables are listed) I got a Plugable USB2-HUB10C2 instead.

Silly me.

It turns out that the USB2-HUB10C2 does support per-port power switching, but _only_ on the two "flip-up" ports, not the other eight. Also, its descriptors don't claim power switching support at all (perhaps because there seems to be no provision for claiming support but only on certain ports), so uhubctl had to be hacked to get it working.

Anyway this is probably not good enough support to get it listed on the compatibility page, but I though I'd mention it just in case anyone went searching the issues list for USB2-HUB10C2.

It's so strange that these smart hubs are so rare. You'd think there'd be a real market for them. Special switchable hubs with out-of-band proprietary power-switch signalling go for hundreds of dollars.

**Comment by mvp** [comment]
Thanks for reporting this. I will close This as not actionable on my part.

If you find any new USB that is supporting per port power switching properly and is not in compatibility list, please report! Thanks!
