### ISSUE TITLE
D-Link DUB-H7 rev D2 (black edition)

### ISSUE THREAD

**Issue by acubino** [mvp/uhubctl#179]
Dear.

D2 revision of DLINK DUB-H7 also working.

Also same USB id:
Bus 001 Device 012: ID 05e3:0608 Genesys Logic, Inc. Hub

Tested power on, power off some devices and works ok.

**Comment by mvp** [comment]
Thanks for your report!
Clarified which revisions are supported in 609d0bcae13f4e3.
