### ISSUE TITLE
ID 05e3:0605 Genesys Logic, Inc. USB 2.0 Hub works

### ISSUE THREAD

**Issue by cron410** [mvp/uhubctl#189]
I'm able to turn off ports with -r 1000 -a 0

**Comment by mvp** [comment]
Genesys Logic Inc is not a hub manufacturer, but chip vendor.
A lot of hubs out there are using this chip, and they all have different behavior with regards to power switching.

Please provide actual manufacturer and product name - as iy typically can be found in online stores like Amazon.

**Comment by mvp** [comment]
Please provide actual hub vendor. Genesys logic is chip vendor, and is shared by many hubs
