### ISSUE TITLE
ID 05e3:0606 ALCOR USB Hub 2.0 works

### ISSUE THREAD

**Issue by cron410** [mvp/uhubctl#190]
I can turn off ports with -a 0 -r 1000

**Comment by mvp** [comment]
Alcor is chip vendor, not hub vendor. Please provide actual product name.

**Comment by mvp** [comment]
Please provide actual hub model. Alcor is chip vendor, not OEM

**Comment by pzskc383** [comment]
hah! found this page while googling for my usb hub's vendor:device.

so, yeah, i can confirm that it works.

OEM seems to be YiChen - https://www.alibaba.com/product-detail/USB-Hub-7-Port-USB-2_1600442366008.html this page shows hub exactly like mine.

it has additional DC connector for +5, pads for filtering capacitors (unpopulated) and 3 pins near IC blob that might be UART, but i haven't checked that.

And for some reason it works only on USB1.1 despite introducing yourself as 'USB 2.0 Hub'

Hope this helps!
