### ISSUE TITLE
uhubctl: command not found after install on Pi

### ISSUE THREAD

**Issue by andrewsleigh** [mvp/uhubctl#195]
Sorry - probably a really simple user error, but I've just installed uhubctl, and when I try to run it I get this error.

I'm installing on a headless Raspberry Pi 4 running Octopi over SSH.

Steps I took (as the user pi, from `/home/pi/`:

```
1. sudo apt-get install libusb-1.0-0-dev
2. git clone https://github.com/mvp/uhubctl
3. cd uhubctl/
4. make
```

These all seemed to work. But then when I try to run it I get this:
```
pi@octopi:~/uhubctl $ uhubctl -a off -p 2
-bash: uhubctl: command not found
```

I'm sure I've done something wrong in the install, but I don't know what. Can you help?

Thanks,
Andrew

**Comment by mvp** [comment]
Either install uhubctl to system path:

   sudo make install

Or use `./uhubctl`. Actually, you will need to use `sudo uhubctl` or `sudo ./uhubctl` unless you fix USB permissions per readme.
