### ISSUE TITLE
Use uhubctl without root?

### ISSUE THREAD

**Issue by phuongnam0907** [mvp/uhubctl#198]
Hi, I'm trying to use your uhubctl on my board and my project is controlling usb (on/off) via using uhubctrl, written by cpp.
I have a problem. When I use commannd "**uhubctl -a on -l 1-1 -p 2**" with root permission (use command "su"), it works. But when I use command of uhubctl without root permission, it failed, and the logcat show 

```
"No compatible smart hubs detected at location 1-1!
Run with -h to get usage info.
There were permission problems while accessing USB.
To fix this, run this tool as root using 'sudo uhubctl',
or add one or more udev rules like below
to file '/etc/udev/rules.d/52-usb.rules':
SUBSYSTEM=="usb", ATTR{idVendor}=="2001", MODE="0666"
then run 'sudo udevadm trigger --attr-match=subsystem=usb'"
```
 
Moreover, my linux kernel doesn't have udev.
So, how can I use uhubctl command without root permission?

**Comment by mvp** [comment]
udev is not part of kernel - it is userspace daemon that can automatically change permissions on device nodes as they are detected by kernel.

If you don't have udev, you need to figure out a way to fix permissions on USB hubs device nodes such that uhubctl can access them - effectively using some other daemon to do what udev does.
