### ISSUE TITLE
Plugable USB2-HUB-AG7

### ISSUE THREAD

**Issue by chvostek** [mvp/uhubctl#20]
The Plugable USB2-HUB-AG7 uses the same chipset as the Plugable USB2-HUB10S which is already listed as compatible. I don't have a HUB10S to test with, but I was able to make `uhubctl` work properly (i.e. list ports and turn things on/off) with modifications shown [here](https://github.com/chvostek/uhubctl/commit/71e4266439c07338b27f92b61e48cd3d5df3d0cf).

While this change works for _me_, it seems like it should break things for others, so I don't want to make a pull request of it yet...  All I can tell for sure is that in [`uhubctl.c` on line 204](https://github.com/mvp/uhubctl/blob/master/uhubctl.c#L204), `lpsm` is set to a value that does not reflect the capabilities of this particular hub.

Any thoughts?

**Comment by mvp** [comment]
Sorry, we cannot list ganged mode hubs. Only per-port power switching mode hubs can be listed as truly supported.
