### ISSUE TITLE
power off command have to be sent twice continuously to work on raspberry 3b+

### ISSUE THREAD

**Issue by gitgayhub** [mvp/uhubctl#203]
`uhubctl -p 4 -a off` this will turn off power of port 4 for less than one second, port power will be back immediately, to permanently shutdown this port, I have to send this command twice  continuously.

I'm using it on raspberry 3b+, system is latest Raspbian

**Comment by mvp** [comment]
This is FAQ https://github.com/mvp/uhubctl/blob/master/README.md#power-comes-back-on-after-few-seconds-on-linux
