### ISSUE TITLE
Raspberry Pi 4 support?

### ISSUE THREAD

**Issue by VSG24** [mvp/uhubctl#204]
Does this program work under Raspberry Pi 4?

**Comment by srijansaxena11** [comment]
+1. Even if it is not completely supported let us know. I currently am using pen drive on one of the USB 3.0 ports. Other 3 ports are available to be used, one of which I have to connect to display/touchscreen which I have to turn off at night by turning off the USB port to which it is connected. Even if both USB 2.0 ports are turned off it is fine.

**Comment by mvp** [comment]
Sorry it took so long to respond, I was traveling.
This is ongoing effort tracked in https://github.com/raspberrypi/linux/issues/3079
We still have improper usb descriptors reported by RPi 4, even after using latest beta firmware.
There is a way to hack it in uhubctl, but it is very kludgy - it would still require you to execute uhubctl twice.
Unfortunately, I don't have RPi 4 to provide reliable fix quickly, but this effort will continue.

**Comment by mvp** [comment]
@VSG24 , @srijansaxena11 , can you please try compiling from rpi4 branch https://github.com/mvp/uhubctl/tree/rpi4?

You may need need to flash new USB firmware https://www.raspberrypi.org/forums/download/file.php?id=33477&sid=d08e808232df0e2ac10eb1af53932f36
per this article: https://www.raspberrypi.org/forums/viewtopic.php?t=258489

You don't need to use patches mentioned in that article, and should not need to use `-e`.
However, power switching may still require turning off power on all ports, e.g.

To turn off:

    sudo uhubctl -a 0 -l 2

To turn on:

    sudo uhubctl -a 1 -l 2

**Comment by mvp** [comment]
Bump: I need someone to try rpi4 fix. I don't have Raspberry Pi 4 (unless you want to send me one 😄 ).
Steps:
1. Flash this USB firmware to your RPi4: https://www.raspberrypi.org/forums/download/file.php?id=33477&sid=d08e808232df0e2ac10eb1af53932f36
2. ```git clone https://github.com/mvp/uhubctl -b rpi4`

**Comment by mvp** [comment]
Thanks to @justinasjaronis providing ssh access to RPi4, I think I have a fix https://github.com/mvp/uhubctl/commit/7277ae4ed72bf3b7dfb1de2bf0e1cc3993393748.
Can someone please try building uhubctl from https://github.com/mvp/uhubctl/tree/rpi4, and try it per instructions above? Thanks!

**Comment by mvp** [comment]
Fix is merged to master 4aae44ced03980802c5fdadcea16d1bc2f8c0bdb.
It is confirmed working by at least 2 other people.

**Comment by radokristof** [comment]
@mvp so it works for all USB ports? The README says that only port 4 will work on an RPi 4.
How can I identify what is the 4th port of the RPi 4?

**Comment by mvp** [comment]
Turning off port 4 kills power on all remaining ports.

**Comment by radokristof** [comment]
Ok so it doesn't matter which port you use, just need to specify port 4 to cut power?

**Comment by mvp** [comment]
Yes. I don't have physical access to rpi4b, you might want to experiment with it yourself :-)

**Comment by radokristof** [comment]
Ok, I'll try :) I want to use a project that uses this, so I don't know how it is handled there, but I'll try.
