### ISSUE TITLE
NOT working: HAMA - 7 port switching USB 2.0 HUB, self-power

### ISSUE THREAD

**Issue by harryzz** [mvp/uhubctl#207]
from lsusb:
ID 04b4:6560 Cypress Semiconductor Corp. CY7C65640 USB-2.0 "TetraHub"

from uhubctl:
Current status for hub 2-1.4, vendor 04b4:6560, 4 ports
   Port 1: 0103 power enable connect 
   Port 2: 0103 power enable connect 
   Port 3: 0303 lowspeed power enable connect 
   Port 4: 0100 power
Current status for hub 2-1, vendor 04b4:6560, 4 ports
   Port 1: 0100 power
   Port 2: 0103 power enable connect 
   Port 3: 0103 power enable connect 
   Port 4: 0503 highspeed power enable connect [04b4:6560]

regards,
harry

**Comment by mvp** [comment]
Please check if VBUS off is supported, follow this FAQ: https://github.com/mvp/uhubctl/blob/master/README.md#how-do-i-check-if-my-usb-hub-is-supported-by-uhubctl

We only add devices which properly support VBUS off into supported devices table.

**Comment by harryzz** [comment]
Sorry not working in this way.

regards

**Comment by mvp** [comment]
No problem, thanks for your report. Please report other hubs if you find anything else compatible and not in the list. Thanks!
