### ISSUE TITLE
Basler USB 3.0 Hub, 4 Ports side by side is supported by uhubctl

### ISSUE THREAD

**Issue by faint069** [mvp/uhubctl#208]
lsusb results:
Bus 002 Device 002: ID 0451:8046 Texas Instruments, Inc. 
Bus 001 Device 002: ID 0451:8044 Texas Instruments, Inc. 

uhubctl result:
Current status for hub 2-1 [0451:8046, USB 3.00, 4 ports]
  Port 1: 06a0 power Rx.Detect
  Port 2: 06a0 power Rx.Detect
  Port 3: 06a0 power Rx.Detect
  Port 4: 06a0 power Rx.Detect
Current status for hub 1-1 [0451:8044 E20E085945C5, USB 2.10, 4 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power

Just checked VBUS power off support by connecting phone and it's working properly

**Comment by mvp** [comment]
Added in c79c9ac - thanks for your report!
