### ISSUE TITLE
DLINK DUB-H4/E also works

### ISSUE THREAD

**Issue by audryste** [mvp/uhubctl#212]
DUB-H4/E Works perfectly :)

**Comment by mvp** [comment]
Can you please provide more details? The following would be helpful:

* output from uhubctl (can be filtered to this hub)
* full model name as printed on the back
* did you test for VBUS off support? https://github.com/mvp/uhubctl#how-do-i-check-if-my-usb-hub-is-supported-by-uhubctl

This is an example of great report https://github.com/mvp/uhubctl/issues/188#issuecomment-553170894

Thanks!

**Comment by mckenfra** [comment]
@audryste If you power-off the USB ports (with the power adapter for the hub plugged in), and then unplug the USB lead to the host computer, do the USB ports stay powered off? Or do they power-on again automatically?

**Comment by mvp** [comment]
Added in b0d321a.
