### ISSUE TITLE
Power-Off Ubertooth Device on Raspberry 4

### ISSUE THREAD

**Issue by csmali** [mvp/uhubctl#213]
Hi, I was dealing with powering off the ubertooth devices on raspberry 4 and I came across with an issue, here is the problem:

I have an ubertooth on port 1-1.4

![ubertooth-working](https://user-images.githubusercontent.com/9373825/73635111-cfd13880-4673-11ea-97df-6b63fe2273c8.jpeg)

Here is the output of uhubctl command

![ubertooth-output](https://user-images.githubusercontent.com/9373825/73635241-22aaf000-4674-11ea-8fb6-bc88a8848a93.jpg)

I am powering off the device, and red light turns off

![ubertooth-power-off-command](https://user-images.githubusercontent.com/9373825/73635375-7289b700-4674-11ea-9e48-50508c4a5db3.jpg)

![ubertooth-powered-off](https://user-images.githubusercontent.com/9373825/73635404-846b5a00-4674-11ea-9454-37e7dad05545.jpeg)

**Here is the problem**

The part I am not understanding is that : I do not know why 2 yellow leds still active although I powered the device off. Also when I plug my mobile phone it keeps charging on that powered off port.

This is the output of lsusb showing that I can per-port switching on 1-1,
![output-of-lsusb](https://user-images.githubusercontent.com/9373825/73635527-c3011480-4674-11ea-96d0-fa4ceb16582d.jpg)

And this is the output of my bootloader version of raspberry since raspberry needs an update for uhubctl.

![vcgen](https://user-images.githubusercontent.com/9373825/73646455-88a27200-468a-11ea-8973-9fb13cf36762.jpg)

If you help me I would be appreciated . Thanks in advance

**Comment by mvp** [comment]
Problem here is that your attempt to turn power off on hub  1-1 doesn't automatically do the same on hub 2 (its dual device). Without this, vbus will not turn off.

Questions:
1. Did you upgrade RPi firmware? vl805 firmware must be 00137ac or later.
2. Did you build uhubctl from master branch? Older binary might not have proper handling for dual devices.
3. Can you please provide container id for RPi 4 USB 2.1 4 port hub? You can find it by looking at `sudo lsusb -v` output, check for container id line.

Workarounds:

It should work if you turn power off/on by 2 commands:

    uhubctl -e -l 1-1 -p 4 -a 0
    uhubctl -e -l 2 -p 4 -a 0

Possible reasons:

  My bet is that container id for dual device is not hardcoded, and might change across models or device batches. I may need to use different hack to make work reliably.

**Comment by csmali** [comment]
Here is the vl805 firmware update code I used 

![uhub-update-code](https://user-images.githubusercontent.com/9373825/73659891-2c4e4b00-46a8-11ea-983f-2dd8ef336b35.jpg)

Output of code update script

![uhub-updated-code](https://user-images.githubusercontent.com/9373825/73660042-77685e00-46a8-11ea-8448-16a75e285141.jpg)

Yes, I used latest master version of uhubctl binary. 

Output of lsusb -v command container ID: 

![container](https://user-images.githubusercontent.com/9373825/73660095-97981d00-46a8-11ea-871c-35fb92766555.jpg)

I tried what you suggested

![uhubctl-command-executed](https://user-images.githubusercontent.com/9373825/73660138-aaaaed00-46a8-11ea-8fce-56d76fd7d7ea.jpg)

It is  still not working unfortunately

![ubertooth-still-working](https://user-images.githubusercontent.com/9373825/73660159-b26a9180-46a8-11ea-9856-b46606bda312.jpg)

**Comment by mvp** [comment]
Your container id shows correctly.

But your firmware still shows 13701 in your picture. It should be 137ac or more.

If fixing firmware version doesn't help, try turning off all 4 ports. That said, turn off port 4 should kill power to all 4 ports anyway.

**Comment by csmali** [comment]
I guess I correctly updated the firmware. But still red led turns off but other 2 yellow led still do not turn off. Since I am not sure, should **vl805** software binary be in a specific folder or something to be able to execute properly?

![updated-firmware](https://user-images.githubusercontent.com/9373825/73718015-64976d00-472c-11ea-9b39-fba99dd2a70e.jpg)

**Comment by mvp** [comment]
You last picture was showing vl805 firmware as 13701. Does it show newer than that now?

As for using ports separately, it is not possible - it's Raspberry Pi 4 hardware limitation as described in FAQ. Closest you can get to this if you downgrade to Raspberry Pi 3B+ - the only model that supports true per-port power switching on 2 out of 4 ports. However, you lose USB 3 support, and get slower hardware.

Alternatively, you can obtain any external hub from supported list, connect your devices via such hub and control power as you wish.

**Comment by csmali** [comment]
Yes I have 137ac now as seen in last picture. I guess I will need external hub. Thanks for your help!
