### ISSUE TITLE
Use `udisksctl` to prevent unintended power-on

### ISSUE THREAD

**Issue by palto42** [mvp/uhubctl#219]
I suffered issues with unintended power-on events, even if I used the additional `udevctl trigger --action=remove ...` as suggested in the README. I could switch off power with `uhubctl`, but after several minutes something turned it on again.

In the last comments of the [blog](http://joeyh.name/blog/entry/usb_drives_with_no_phantom_load/#comment-cf65489bf41c1e6035efa9d68a0ad474) referenced in the README I found an alternative command `udisksctl power-off --block-device /dev/disk/...` which does a better job on my Ubuntu 18.04 server. I issue this command before turning off the port with `uhubctl` and don't get the unexpected power-on anymore since.

I think it would help other user with such auto-power-on issues if the `udiskctl` command option would be added on the README page.

**Comment by mvp** [comment]
Thanks, mentioned it in d576db98fbff8f5.
