### ISSUE TITLE
Specific device still has power on after disabling a port

### ISSUE THREAD

**Issue by evantsik** [mvp/uhubctl#222]
Hey guys,

I am using the library on MacOS with the USB3-HUB7C hub (its on the list).
I have a device which keeps getting power even when I disable the power for the port.
So lets say I have the port number 2 and I have any other device connected. If I disable it with the uhubctl -a off -p 2, the device will stop getting power (led's will turn off). BUT if I connect my *specific* device on this port and do the same the device's led's will stay on (I can still see it active on IORegistryExplorer,  unlike all the other devices which disappear when I turn off the port). 
Any idea what could possibly be wrong and how I could fix it?

Thank you!

**Comment by mvp** [comment]
Oops, you deleted it before I had a chance too look :-)
I hope your issue is resolved. If not, please ask.
