### ISSUE TITLE
Command not Found 

### ISSUE THREAD

**Issue by moboch** [mvp/uhubctl#225]
I tried using uhubctl on my Raspberry Pi 3b but running `sudo uhubctl` gives me an error which says command not found. Running `make` on the other hand says uhubctl is up to date. What am I doing wrong?

**Comment by mvp** [comment]
Few ways to fix it:
On Linux/Mac, you have to use ./ to execute commands in current directory (it's not in search PATH by default).
To fix:

1. Install uhubctl as system command into `/usr/sbin/uhubctl` using `sudo make install`
2. Use `sudo ./uhubctl`

Also consider configuring udev permissions per FAQ, so you don't need to use sudo as well.
