### ISSUE TITLE
Raspberry Pi 4B - layout change with latest bootloader

### ISSUE THREAD

**Issue by touche112** [mvp/uhubctl#233]
With bootloader version `000137ad`, all ports must be set by uhubctl in order power to be cut.  Triggering only port 4 no longer has any effect.

Current command in readme:
`uhubctl -l 1-1 -p 4 -a 0`

Actual command required to cut power:
`uhubctl -l 1-1 -p 1-4 -a 0`

As always, this triggers the entire gang.

**Comment by mvp** [comment]
Thanks for your report, doc fixed
