### ISSUE TITLE
Hub successful [05ac:1010 Apple Inc. USB3.0 Hub, USB 3.00, 1 ports]

### ISSUE THREAD

**Issue by AbdulAli** [mvp/uhubctl#240]
The following Hub is working successfully.
[05ac:1010 Apple Inc. USB3.0 Hub, USB 3.00, 1 ports]

Details: Running `uhubctl`

> Current status for hub 20-1 [05ac:1011 Apple Inc. USB2.0 Hub, USB 2.10, 2 ports]
> Port 1: 0103 power enable connect [2ab9:0001 Monsoon Solutions Inc. Mobile Device Power Monitor 65500]
> Port 2: 0303 power lowspeed enable connect [05ac:1461 Apple Inc. USB-C VGA Multiport Adapter DLC633501PCG2WFAM]
> Current status for hub 0-1 [05ac:1010 Apple Inc. USB3.0 Hub, USB 3.00, 1 ports]
> Port 1: 02a0 power 5gbps Rx.Detect

Running `uhubctl -a cycle -p 1 -d 5`. Waits for 5 seconds and restart the hub.

> Current status for hub 20-1 [05ac:1011 Apple Inc. USB2.0 Hub, USB 2.10, 2 ports]
>   Port 1: 0103 power enable connect [2ab9:0001 Monsoon Solutions Inc. Mobile Device Power Monitor 65500]
> Sent power off request
> New status for hub 20-1 [05ac:1011 Apple Inc. USB2.0 Hub, USB 2.10, 2 ports]
>   Port 1: 0000 off
> Current status for hub 0-1 [05ac:1010 Apple Inc. USB3.0 Hub, USB 3.00, 1 ports]
>   Port 1: 02a0 power 5gbps Rx.Detect
> Sent power off request
> New status for hub 0-1 [05ac:1010 Apple Inc. USB3.0 Hub, USB 3.00, 1 ports]
>   Port 1: 00a0 off
> Current status for hub 20-1 [05ac:1011 Apple Inc. USB2.0 Hub, USB 2.10, 2 ports]
>   Port 1: 0000 off
> Sent power on request
> New status for hub 20-1 [05ac:1011 Apple Inc. USB2.0 Hub, USB 2.10, 2 ports]
>   Port 1: 0101 power connect [2ab9:0001]
> Current status for hub 0-1 [05ac:1010 Apple Inc. USB3.0 Hub, USB 3.00, 1 ports]
>   Port 1: 00a0 off
> Sent power on request
> New status for hub 0-1 [05ac:1010 Apple Inc. USB3.0 Hub, USB 3.00, 1 ports]
>   Port 1: 02a0 power 5gbps Rx.Detect

**Comment by mvp** [comment]
I have this adapter, and unfortunately, it does not support VBUS off. connected phone still continues to charge even after turning port off.
We only add devices that support VBUS off, and this will not add this one to supported list.
You can certainly use it reset data connections, but not power.
