### ISSUE TITLE
Add D-link DUB-H7 rev E to the list

### ISSUE THREAD

**Issue by jaim46** [mvp/uhubctl#244]
I tried the D-link DUB-H7 rev E - and it works! You can add this one to the list.

Best regards,

Jaim

**Comment by mvp** [comment]
Did you have a chance to test VBUS off for this hub?

**Comment by jaim46** [comment]
No sorry, was to busy. I'll try on Monday!

Verstuurd vanaf mijn iPhone

**Comment by mvp** [comment]
Any update on vbus off support?

**Comment by badcloud** [comment]
Just received my D-Link HUB-7 rev E1, I can confirm that vbus off support works :)

**Comment by jaim46** [comment]
Great! Sorry I didn’t get to test it. Was too busy at work.

Thanks for your great work,

Jaim

**Comment by mvp** [comment]
Thanks for reporting, added to the list :-)

**Comment by peterdey** [comment]
@badcloud Is the E1 you have the skinny model (as opposed to the larger, black Rev D) ?
![DUB-H7-E1A](https://user-images.githubusercontent.com/5979944/150321777-473d72ce-0fec-42a5-99c4-82ad46c741a0.jpg)

**Comment by vpeter4** [comment]
Anyone knows which revision exactly works? I have available only E7 in shops.
