### ISSUE TITLE
Are Amazon basics HUC9002V1ESL & HU9002V1ESL the same?

### ISSUE THREAD

**Issue by Roeeklinger60** [mvp/uhubctl#246]
Hey,

I just went over the table and you list HUC9002V1ESL as working, going into Amazon.de website I can see 2 versions, one that comes with a USB-B - USB-A cable listed as HU9002V1ESL and another that comes with a USB-B - USB-C cable that is listed as HUC9002V1ESL.

Are they essentially the same but only come with a different cable? Will connecting a USB-B to USB-A cable work with the HUC9002V1ESL?

If nobody knows about the HU9002V1ESL I can make an order and let you know so you can update the table.

**Comment by mvp** [comment]
I assume they are the same. But I don't own either one. Please check and report! Thanks

**Comment by Roeeklinger60** [comment]
@mvp I ended up getting the HUC9002V1ESL and it is working great as expected. However, toilver opened an issue here and he had the HU9002V1ESL and it worked the same. 99% sure this is the same hub with different USB-B cables. (one comes with USB-A and one comes with USB-C), maybe the second model should be added to the table as well.

**Comment by mvp** [comment]
Much thanks for reporting. I will update the table
