### ISSUE TITLE
Not working on a RPI4 4GB

### ISSUE THREAD

**Issue by Tsjippy** [mvp/uhubctl#251]
Hi,

I am on the latest firmware of the RPI4.
When I try to turn off the power to the usb ports it does not work:
`sudo ./uhubctl -l 1 -p 4 -a 0`

gives result:
"Current status for hub 1 [1d6b:0002 Linux 4.19.118-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0]
Sent power off request
New status for hub 1 [1d6b:0002 Linux 4.19.118-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0]
"

However the power is still on

`sudo ./uhubctl -l 2 -p 4 -a 0 -r 100
No compatible smart hubs detected at location 2!
Run with -h to get usage info.
`

`sudo ./uhubctl
Current status for hub 2 [1d6b:0003 Linux 4.19.118-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 3.00, 4 ports]
  Port 1: 0080 off
  Port 2: 0080 off
  Port 3: 0080 off
  Port 4: 0080 off
Current status for hub 1 [1d6b:0002 Linux 4.19.118-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0]
  Port 1: 0000 off
`

**Comment by mvp** [comment]
You need to build from master branch (version 2.2.0 or later). After that, follow readme: `sudo uhubctl -l 2 -a 0` should work.
