### ISSUE TITLE
supported devices?

### ISSUE THREAD

**Issue by AndreV84** [mvp/uhubctl#256]
are these hubs supported?
https://www.amazon.com/gp/product/B083XTKV8V/ref=ppx_yo_dt_b_%C3%A7%C3%A7asin_title_o04_s00?ie=UTF8&psc=1
https://www.amazon.com/gp/product/B00XMD7KPU/ref=ppx_yo_dt_b_asin_title_o04_s00?ie=UTF8&psc=1
is it possible to use it to power on off ports on nvidia jetson?

**Comment by mvp** [comment]
All known supported devices are in current compatibility list. That said, many new devices might be supported, including ones you mention. Please give it a try a report back if they work. Thanks
