### ISSUE TITLE
D-Link DUB-H4 H/W Ver.: F1 any chance?

### ISSUE THREAD

**Issue by emard** [mvp/uhubctl#257]
I have D-Link DUB-H4 , on the box is written H/W Ver.: F1
and uhubctl doesn't recognize it.
A friend has D-Link DUB-H4 Ver.: D2 and uhubctl works

Any chance that F1 will work as being newer or should I try
to get replacement with D2?

**Comment by mvp** [comment]
If `sudo uhubctl` doesn't list your hub, it won't work :-(.
Check devices table for exact list of supported models and revisions.
