### ISSUE TITLE
DLink DUB-H4 rev F/F1 - working only with ganged power switching

### ISSUE THREAD

**Issue by goski89** [mvp/uhubctl#259]
I checked wHubCharacteristic parameter (0x0000 - Ganged power switching) and also make some tests to be sure.
idVendor: 0s1a40
idProduct: 0x0101

lsusb-v: [https://gist.github.com/goski89/ad5f9d286a8cbd706acb12d009b67cab](https://gist.github.com/goski89/ad5f9d286a8cbd706acb12d009b67cab)

**Comment by mvp** [comment]
Thanks, updated README!
