### ISSUE TITLE
Allow uhubctl to run on incompatible hubs

### ISSUE THREAD

**Issue by wtolkien** [mvp/uhubctl#260]
First, thanks for this very useful tool!

If I'm not mistaken, currently uhubctl looks at the 'Per-port power switching' flag to decide if a hub is compatible. 

I'd like to suggest that uhubctl no longer refuses to operate on incompatible hubs, but merely outputs a warning. 

The reason is that from my experience, even if a hub does not support real power switching, it still does a port reset which usually triggers a reset of the attached USB device. And that's a useful feature. 

This 'port reset only' actually happens a lot. Right now, very often a hub has the 'Per-port power switching' flag set without actually really supporting it. In this case uhubctl will already trigger a port reset. Not perfect, but the best it can do! 

Why not allow this on all hubs?

Thanks!

**Comment by mvp** [comment]
Thanks for the idea, I will consider adding it. Not promising when though.

**Comment by wtolkien** [comment]
Thanks - much appreciated! Alternatively there could be a '--force' option to run on incompatible hubs.

**Comment by henzef** [comment]
I managed to switch a D-Link DUB-H4 F-Revision hub (which only supports ganged power switching) on and off with a hack. See https://github.com/mvp/uhubctl/issues/268#issuecomment-694095968

**Comment by mvp** [comment]
Implemented in 0cc0929.
