### ISSUE TITLE
Pi4, USB-C Port

### ISSUE THREAD

**Issue by ganzgustav22** [mvp/uhubctl#266]
Will (or should) this tool cut and restore power on the Pi4 USB-C Port also?

According to https://github.com/mvp/uhubctl#raspberry-pi-4b
`uhubctl -l 3 -p 1 -a 0`
should cut power. When I type this, I can see the device disappear in dmesg:
```
[  184.239568] dwc2 fe980000.usb: Not connected
[  184.239593] usb 3-1: usbfs: usb_submit_urb returned -19
[  184.239637] dwc2 fe980000.usb: Not connected
[  184.239652] usb 3-1: usbfs: usb_submit_urb returned -19
[  184.315865] usb 3-1: USB disconnect, device number 2

```

When running `uhubctl -l 3 -p 1 -a 1` it doesn't come back though.

Edit, sorry forgot to add:

Using Raspberry Pi OS 2020-05-27:

```
Linux 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux

BCM2711 detected
BOOTLOADER: up-to-date
CURRENT: Thu 16 Apr 17:11:26 UTC 2020 (1587057086)
 LATEST: Thu 16 Apr 17:11:26 UTC 2020 (1587057086)
 FW DIR: /lib/firmware/raspberrypi/bootloader/critical
VL805: up-to-date
CURRENT: 000137ad
 LATEST: 000137ad

```

**Comment by ganzgustav22** [comment]
Well, I've measured with a multimeter on TP1 now (I think this is the testpad that is connected to the USB +5V line?), but the power doesn't get cut off. Also I can measure 0 Ohm between TP1 and the +5V line on the GPIO header, that means it's parallel and the power cannot be controlled via software, or?

**Comment by mvp** [comment]
uhubctl can see this device advertising power switching support, and is able to send a request to turn power off.

However, it seems that underlying chip is missing necessary circuitry to actually cut the power on otg line.

I don't know internal details of pi4 otg chip, perhaps @p33m or @slysven know more about pi4 hardware and can shed some light?

**Comment by P33M** [comment]
There is no power switching facility on Pi 4's USB-C port.

**Comment by mvp** [comment]
Thanks @P33M for confirmation. I will change readme to mention that

**Comment by ganzgustav22** [comment]
Thanks for your quick help guys.
