### ISSUE TITLE
USB spec translation request, s'il vous plaît

### ISSUE THREAD

**Issue by seamusdemora** [mvp/uhubctl#271]
I'm considering [this hub](https://www.digikey.com/htmldatasheets/production/1879845/0/0/1/2991.html) with this [data sheet](https://cdn-shop.adafruit.com/product-files/2991/FE1.1s+Data+Sheet+(Rev.+1.0).pdf). The only obvious mention of power management in the spec sheet is this:

>Automatic self-power status monitoring;
>Automatic re-enumeration when Self-Powered switching to Bus-Powered; 

### Q: Does this mean the hub supports "per-port power switching" à la `uhubctl`?

**Comment by mvp** [comment]
Unfortunately, it is not possible to tell until you try it.

Almost all USB chips in existence can support PPPS, but they allow hub manufacturer to disable adverisement.
That said, some hub vendors don't bother doing even that. In these cases, hub may still advertise PPPS, but may not work if vendor did not put proper circuitry in place.

So I just recommend to follow this FAQ item: https://github.com/mvp/uhubctl#how-do-i-check-if-my-usb-hub-is-supported-by-uhubctl
