### ISSUE TITLE
Power on/off partial USB port in raspberry pi 3 B+

### ISSUE THREAD

**Issue by JinyongJeong** [mvp/uhubctl#275]
I am testing `uhubctl` to control usb port in raspberry pi 3 b+

`uhubctl -l 1-1 -p 2 -a 0` and `uhubctl -l 1-1 -p 2 -a 1` is work for me.

But this command control all 4 port simultaneously. 

I check all closed issue, but I can't find any way to control usb port partially. 
(ex, I'd like to on and off for only 2 usb port)

Is it impossible?

**Comment by mvp** [comment]
This is hardware limitation of Raspberry Pi https://github.com/mvp/uhubctl#raspberry-pi-turns-power-off-on-all-ports-not-just-the-one-i-specified
