### ISSUE TITLE
Add IC USB2534 to supported list - tested and functional

### ISSUE THREAD

**Issue by littlehill** [mvp/uhubctl#277]
The board i am using has USB2534 and tool helped me a lot.
Reporting another tested piece. All 4 ports.
Regards
---
ID 0424:2534 Standard Microsystems Corp.
..
wHubCharacteristic 0x0009
    Per-port power switching
    Per-port overcurrent protection
..
#root#>> uhubctl -l 1-1 -p 1 -a 0
Current status for hub 1-1 [0424:2534, USB 2.01, 4 ports]
  Port 1: 0103 power enable connect [0457:1080 Silicon Integrated System Co. SiS HID Controller 123456789@A]
Sent power off request
New status for hub 1-1 [0424:2534, USB 2.01, 4 ports]
  Port 1: 0000 off

#root#>>  uhubctl -l 1-1 -p 1 -a 1
Current status for hub 1-1 [0424:2534, USB 2.01, 4 ports]
  Port 1: 0000 off
Sent power on request
New status for hub 1-1 [0424:2534, USB 2.01, 4 ports]
  Port 1: 0100 power

note: the devixce takes a second to rerest so full detection happens later.

**Comment by mvp** [comment]
Thanks for reporting!

Can you please confirm vbus off support per https://github.com/mvp/uhubctl#how-do-i-check-if-my-usb-hub-is-supported-by-uhubctl?

**Comment by seamusdemora** [comment]
@mvp: Support for *per-port-switching* is a decision by the designer/manufacturer obviously, but is *per-port-switching* supported by all USB chipsets - or just a subset? In other words, if a designer/mfr chose the "wrong" chipset, would that take away the option for providing *per-port-switching* as a feature? Could the driver be a factor in this?

**Comment by mvp** [comment]
@seamusdemora, actually this is off topic for this issue. That said, to the best of my knowledge, all USB chipsets do support per-port power switching. However, they can be configured by manufacturer to disable such support to match real hardware capabilities. Some vendors configure it improperly - e.g. advertise PPPS support when actual circuitry is missing.

**Comment by mvp** [comment]
@littlehill, can you please confirm if vbus off is supported for this hub per https://github.com/mvp/uhubctl#how-do-i-check-if-my-usb-hub-is-supported-by-uhubctl?

**Comment by littlehill** [comment]
> @littlehill, can you please confirm if vbus off is supported for this hub per https://github.com/mvp/uhubctl#how-do-i-check-if-my-usb-hub-is-supported-by-uhubctl?

Greetings, yes i can confirm that the IC functionality is there.

**Comment by mvp** [comment]
@littlehill , my question is not whether chip reports power switching, but if voltage is actually turning off for your hub.

**Comment by littlehill** [comment]
Greetings, yes, thats what i mean, i see the voltage switching. On per-port basis. Was able to hook osciloscope on and in both cases with & without a device connected it does switch the voltage as expected.
Sorry for not being clear about this from start.
The hub has EN/OC functionality in 1 pin, so power switch AP2553A is used. (Just basically a transistor with OC limit)
The hub controlls the behaviour and switches power on/off. Measured on HW.

**Comment by mvp** [comment]
Thanks @littlehill, added this hub to the list in 77d8851.
