### ISSUE TITLE
Generic "USB2.0 Compact Hub", UH204B06050526 has per port switching

### ISSUE THREAD

**Issue by brentfraser** [mvp/uhubctl#278]
Generic "USB2.0 Compact Hub", UH204B06050526:
Cypress | CY7C65640 USB-2.0 "TetraHub" | 4 | 2.0 | 04B4:6560 | 2009

**Comment by mvp** [comment]
Thanks for reporting!

Can you please confirm vbus off support per https://github.com/mvp/uhubctl#how-do-i-check-if-my-usb-hub-is-supported-by-uhubctl?

**Comment by brentfraser** [comment]
Crap.  The vbus test did not work.   Sorry for the noise.

**Comment by mvp** [comment]
No worries. Please check and report other hubs if you bump into working one. Thanks!
