### ISSUE TITLE
Can the hardware be damaged by repeatedly powering USB hubs on and off?

### ISSUE THREAD

**Issue by passuf** [mvp/uhubctl#279]
Thanks for providing this great library! I am using it on my Raspberry Pi 4 to monitor the state of an `autofs` share (connected to an external RAID case) and power off the corresponding USB hub whenever the share is idle for a certain amount of time. It all works great, however, my watchdog sends the power off command via `uhubctl` approximately every 15 minutes, even if the USB hub is already powered off.

My question: Is there a side effect when powering off the USB hub repeatedly? Since there is a `cycle` option I would assume this is fine, I just want to make sure I am not damaging the Raspberry Pi in doing so.

Thanks a lot for your help!

**Comment by mvp** [comment]
It should not damage anything. I've been using it for months and years running large number of hubs doing many switches an hour without any all effects. However, it was not Raspberry Pi, but I never heard anyone reporting damaging Raspberry Pi this way.
