### ISSUE TITLE
Keep power OFF on device connection

### ISSUE THREAD

**Issue by nunojpg** [mvp/uhubctl#281]
I want to only manually enable the power for a port, including on boot (equivalent if device is plugged in) instead of getting it default enabled on enumeration.

Currently I see my option really limited to patch the kernel drivers/usb/core/hub.c to inhibit USB_PORT_FEAT_POWER.

Looking for any easier/flexible suggestion :)

**Comment by mvp** [comment]
You can add `uhubctl` call into `/etc/rc.local` to turn off power at boot, and re-enable it only as you wish.

That said, Linux will probably still be able to turn power on at boot for very short period of time.
I don't think you can avoid this without patching Linux kernel.
Alternatively, you might be able to initialize USB stack later (by using loadable kernel modules perhaps?).

At any rate, this is beyond scope of what uhubctl can possibly do :-(
