### ISSUE TITLE
[SUPPORTED] Anker 7 Port USB 3.0 Hub

### ISSUE THREAD

**Issue by rdica** [mvp/uhubctl#287]
Anker 7-Port USB 3.0 Data Hub with 36W Power Adapter and BC 1.2 Charging Port

Model: `AK-68ANHUB-BV7A-0004`
Date available: `January 30, 2014`
EOL: `No`
VBUS off support: `Yes`

    uhubctl -l 1-3 -a off -p 1
    Current status for hub 2-3.4 [2109:0812 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
      Port 1: 02a0 power 5gbps Rx.Detect
    Sent power off request
    New status for hub 2-3.4 [2109:0812 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
      Port 1: 0080 off
    Current status for hub 1-3 [2109:2812 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
      Port 1: 0503 power highspeed enable connect [1e4e:0109 Etron Technology, Inc. USB2.0 Camera]
    Sent power off request
    New status for hub 1-3 [2109:2812 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
      Port 1: 0000 off

    uhubctl -l 1-3 -a on -p 1
    Current status for hub 2-3.4 [2109:0812 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
      Port 1: 0080 off
    Sent power on request
    New status for hub 2-3.4 [2109:0812 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
      Port 1: 02a0 power 5gbps Rx.Detect
    Current status for hub 1-3 [2109:2812 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
      Port 1: 0000 off
    Sent power on request
    New status for hub 1-3 [2109:2812 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
      Port 1: 0101 power connect [1e4e:0109]

    uhubctl 
    Current status for hub 2-3.4 [2109:0812 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
      Port 1: 02a0 power 5gbps Rx.Detect
      Port 2: 02a0 power 5gbps Rx.Detect
      Port 3: 02a0 power 5gbps Rx.Detect
      Port 4: 02a0 power 5gbps Rx.Detect
    Current status for hub 2-3 [2109:0812 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
      Port 1: 02a0 power 5gbps Rx.Detect
      Port 2: 02a0 power 5gbps Rx.Detect
      Port 3: 02a0 power 5gbps Rx.Detect
      Port 4: 0263 power 5gbps U3 enable connect [2109:0812 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports]
    Current status for hub 1-3.4 [2109:2812 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
      Port 1: 0100 power
      Port 2: 0100 power
      Port 3: 0100 power
      Port 4: 0100 power
    Current status for hub 1-3 [2109:2812 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
      Port 1: 0100 power
      Port 2: 0100 power
      Port 3: 0103 power
      Port 4: 0507 power highspeed suspend enable connect [2109:2812 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]

**Comment by mvp** [comment]
Thanks, added to the list
