### ISSUE TITLE
RPi3: port numbering issue

### ISSUE THREAD

**Issue by chrissyan0** [mvp/uhubctl#293]
Thank you for providing uhubctl!

I just compiled the latest release on a raspberry pi 3 model b rev 1.2.
**sudo ./uhubctl** says
Current status for hub 1-1 [0424:9514, USB 2.00, 5 ports, ppps]
  Port 1: 0503 power highspeed enable connect [0424:ec00]
  Port 2: 0100 power
  Port 3: 0103 power enable connect [10c4:ea60 Silicon Labs ELV HQ-Stereo-UKW-Pr?fgenerator SUP2]
  Port 4: 0100 power
  Port 5: 0100 power
Current status for hub 1 [1d6b:0002 Linux 5.4.79-v7+ dwc_otg_hcd DWC OTG Controller 3f980000.usb, USB 2.00, 1 ports, ppps]
  Port 1: 0503 power highspeed enable connect [0424:9514, USB 2.00, 5 ports, ppps]

To shutdown the SUP2 on port 3, I try
**sudo ./uhubctl -a off -l 1-1 -p 3**
Current status for hub 1-1 [0424:9514, USB 2.00, 5 ports, ppps]
  Port 3: 0103 power enable connect [10c4:ea60 Silicon Labs ELV HQ-Stereo-UKW-Pr?fgenerator SUP2]
Sent power off request
New status for hub 1-1 [0424:9514, USB 2.00, 5 ports, ppps]
  Port 3: 0000 off

But physically, it didn't turn it off. To achive that, I have to do it on port 2

**sudo ./uhubctl -a off -l 1-1 -p 2**
Current status for hub 1-1 [0424:9514, USB 2.00, 5 ports, ppps]
  Port 2: 0100 power
Sent power off request
New status for hub 1-1 [0424:9514, USB 2.00, 5 ports, ppps]
  Port 2: 0000 off

Kind regards
Chris

**Comment by mvp** [comment]
This is FAQ https://github.com/mvp/uhubctl#raspberry-pi-b2b3b

Raspberry Pi B+,2B,3B

    Single hub 1-1, ports 2-5 ganged, all controlled by port 2:

    uhubctl -l 1-1 -p 2 -a 0

    Trying to control ports 3,4,5 will not do anything.
