### ISSUE TITLE
Add j5create JUH340 to supported hubs

### ISSUE THREAD

**Issue by polarisity** [mvp/uhubctl#294]
The following hub has been tested with attached commands. https://en.j5create.com/products/juh340

![pppc](https://user-images.githubusercontent.com/1537479/101757065-ac87dd00-3b11-11eb-8004-bd8c25c0bb72.png)
![pppc1](https://user-images.githubusercontent.com/1537479/101757076-aeea3700-3b11-11eb-8742-aefd319007f6.png)

**Comment by mvp** [comment]
Sorry, not adding ganged hubs

**Comment by mvp** [comment]
Basically, `-f` means operate on unsupported hubs. And if they are unsupported, they are not something we will track.
