### ISSUE TITLE
AmazonBasics USB 3.1 Type-C to 4-Port Aluminum Hub Connector, Silver does not work with uhubctl

### ISSUE THREAD

**Issue by slimjet** [mvp/uhubctl#296]
Item number: L6LUD018-CS-R 
Will not turn off a dumb usb light.
[Link](https://www.amazon.com/gp/product/B074ZTJNXX/ref=ppx_yo_dt_b_asin_title_o06_s02?ie=UTF8&psc=1)

**Comment by mvp** [comment]
This hub is not listed as supported in first place. Sorry, we don't list unsupported hubs, as this will make such list too large.
