### ISSUE TITLE
How can I give support?

### ISSUE THREAD

**Issue by loveyourfeelings** [mvp/uhubctl#297]
Hello,

I am facing a problem where I need to selectively switch on/off the 4 ports, not all together, just 1 by 1. I can complain switching on/off USB 2.0 hub and USB 3.0 hub separately, but I can not complain switching both on/off always (that is happening now).

I am using raspberry pi 4, I have pi b+. I need to give support to one of the two hubs I have. I have one amazon basics which is not listed and I have another usb 3.0 (the amazon is 2.0) with power supply.

By now I haven't switched any on/off by port. I was able to switch all ports on raspberry pi 4 and b+ but not only 2.0 on pi 4 and 3.0 on pi 4 sepparately. I don't want to buy any raspberry pi more, I prefer to use pi 4. But... seems very beta and not working or IDK how to do it properly.

Please, can you help me in creating a new support for my usb hubs or can you just tell me how to use it properly on raspberry pi 4?

I have read the following link https://stackoverflow.com/questions/59772765/how-to-turn-usb-port-power-on-and-off-in-raspberry-pi-4

But I still unable to switch on/off hub 2.0 and 3.0 separately.
Preferably I want to switch 1 by 1 in raspberry pi, but at is not implemented, then just in a hub 2.0 and 3.0 of pi 4 and in a hub separately.

Can it be?

Thanks in advance!
Have a nice day.

**Comment by mvp** [comment]
You cannot switch ports individually on Raspberry Pi itself (any model), only all ports at once - that is hardware limitation of Raspberry Pi itself.

However, you can attach any of hubs listed is supported list to your Raspberry Pi, and control ports individually. 
If hub is not listed, it's not guaranteed to work.
Please make sure to build uhubctl from master branch, it has fixes important for USB3. I'm going to release version 2.3.0 soon, it will have those fixes in.
