### ISSUE TITLE
New supported smarthub 2109:2813 Aukey CB-C59

### ISSUE THREAD

**Issue by Hanjecom** [mvp/uhubctl#299]
Reporting an unlisted smarthub: Aukey CB-C59 (bought via Amazon)
http://test.aukey.com/products/usb-c-to-3-port-usb-3-0-hub-with-hdmi-card-reader-usb-c-charing-port-cb-c59

uhubctl:
Current status for hub 1-1.5 [2109:2813 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0507 power highspeed suspend enable connect [1a40:0101 USB 2.0 Hub, USB 2.00, 4 ports]

lsusb output:
Bus 001 Device 044: ID 2109:2813 VIA Labs, Inc.
...
Hub Descriptor:
  bLength               9
  bDescriptorType      41
  nNbrPorts             4
  wHubCharacteristic 0x00e9
    Per-port power switching
    Per-port overcurrent protection
    TT think time 32 FS bits
    Port indicators
  bPwrOn2PwrGood       50 * 2 milli seconds
  bHubContrCurrent    100 milli Ampere
  DeviceRemovable    0x00
  PortPwrCtrlMask    0xff

Tested VBUS, shutting down 1 port actually cuts off power

**Comment by mvp** [comment]
Thank you for reporting! Added in 4b663f3.
