### ISSUE TITLE
 D-Link: DUB-H7 new Black edition compatibility

### ISSUE THREAD

**Issue by swapna-chennadi** [mvp/uhubctl#3]
Is there any specific reason behind incompatibility of D-Link: DUB-H7 new Black edition ?
I have a bunch of these Hubs which I intent to reset.
Would appreciate any pointers to make this work.

**Comment by mvp** [comment]
There is no specific reason except that DUB-H7 Black edition does not support per port power control, which makes it impossible to turn power on ports off or on.
In general, you can check if uhubctl supports your hub by connecting it to your computer and running `uhubctl`. If hub is supported, it will be listed - simple as that.
