### ISSUE TITLE
Doesn't work on Raspberry pi 4B

### ISSUE THREAD

**Issue by Spyman** [mvp/uhubctl#301]
After update doesn't work on Raspberry pi 4B. 
"sudo uhubctl" output: 

Current status for hub 2 [1d6b:0003 Linux 5.4.79-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 3.00, 4 ports]
  Port 1: 0080 off
  Port 2: 0080 off
  Port 3: 0080 off
  Port 4: 0080 off
Current status for hub 1 [1d6b:0002 Linux 5.4.79-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 2.00, 1 ports]
  Port 1: 0507 power highspeed suspend enable connect [2109:3431 USB2.0 Hub, USB 2.10, 4 ports]
  
  All ports enabled. 
  "uhubctl -a 0" has no effect. 
  
"sudo uhubctl -l 1-1 -a 0" output: 

No compatible smart hubs detected at location 1-1!
Run with -h to get usage info.

eeprom version - 000138a1

**Comment by mvp** [comment]
Make sure you use latest version 2.3.0. Your output is not consistent with that version

**Comment by mvp** [comment]
After you get version 2.3.0 installed/compiled, please post output of `sudo uhubctl`

**Comment by Spyman** [comment]
Thank you.
Not the latest version was in the binary repository.
Everything works in the sources compiled from the gita.
