### ISSUE TITLE
quiet mode

### ISSUE THREAD

**Issue by cainbantam** [mvp/uhubctl#302]
Hello,
thanks for the great tool. Would it be possible to add a silent mode, for I've heard that this is a requirement if we want cron to be able to use it (I have a made a script using the uhubctl command which fails to be run by cron and this might be the reason why...)
I may have solved the issue though... adding > /dev/null after the command.
Thank you for your work!

**Comment by mvp** [comment]
It should work from cron already, few issues you should pay attention to:

* Be sure to specify full path to uhubctl executable in your cron invocation, e.g. `/usr/sbin/uhubctl`
* Be sure that you have either configured udev USB permissions as described in readme, or run uhubctl as root (it should be already the case if you run it from root's crontab)
* By default, cron will send email with output of called executable. You can mute it by either assigning MAILTO="" at the beginning of crontab, or by redirecting stdout/stderr to `/dev/null`, e.g.

    uhubctl -l 1-1 -p 2 -a 0 >/dev/null 2>&1

**Comment by cainbantam** [comment]
great! Thank you for those further advices!
