### ISSUE TITLE
Targus PAUH212

### ISSUE THREAD

**Issue by locostudios** [mvp/uhubctl#311]
Bought this hub in hope of it working with Virtualhere and an iLok dongle. Haven't tried the VBUS thing cause i dont have a fan, light or a suitable cable to charge my phone in my studio at the moment, but the iLok is working fine remotely, and apparently it is dependent on a power cycling port.  I guess its safe to say this is working, especially since you already have the one with the "U" behind in your list already.

**Comment by locostudios** [comment]
I've tried a few other hubs that turned out incompatible, or at least not working with an iLok. I list them here, might be useful for others.

Deltaco SuperSpeed Hub UH-472 Rev4
ORICO A3H7-US-BK
Hama 00078492

**Comment by mvp** [comment]
Thanks for reporting! Added a note in device list about it.
