### ISSUE TITLE
Unsupported hubs

### ISSUE THREAD

**Issue by lyngklip** [mvp/uhubctl#312]
I think it would be useful with a list of hubs reported as not working. I'll submit to you the "Likorlove USB Hub 3.0 7 Ports":

https://www.amazon.de/Likorlove-Datenhub-Verteiler-Einzelnen-Ultrabooks/dp/B07C1VSJLT/

This is reported as [2109:2815 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ganged]

Not sure why it's reported as a 2.0, it should be 3.0...

It can be switched manually and I have had no issues with it. I may take it apart some day and se what's on the inside.  It does seem to be glued together though.

  wHubCharacteristic 0x00e0
    Ganged power switching
    Ganged overcurrent protection
    TT think time 32 FS bits
    Port indicators

Ganged switching doesn't seem to work though (tried all ports)

**Comment by mvp** [comment]
Sorry, there is no way I could maintain list of unsupported hubs - it will be many times larger than list of supported ones. Added a note in README about it.
