### ISSUE TITLE
pkg-config from env variable in Makefil

### ISSUE THREAD

**Issue by coconutruben** [mvp/uhubctl#315]
For the Makefile, the fact that this is calling `pkg-config` directly is causing issues with some of our toolchains on chromium os. Could you add a `PKG_CONFIG ?= pkg-config` line so that the build-scripts can pass our wrapped pkg-config?

**Comment by mvp** [comment]
Implemented in 92736a8.

**Comment by coconutruben** [comment]
thank you so much, that's so quick! could it be possible to release 2.3.1 with this fix (and should I file an issue for that?)

**Comment by mvp** [comment]
I should release 2.4.0 tomorrow. There is toggle feature that is still unreleased.

**Comment by coconutruben** [comment]
awesome, thank you!

**Comment by mvp** [comment]
@coconutruben, uhubctl 2.4.0 has been released, and contains this change https://github.com/mvp/uhubctl/releases/tag/v2.4.0
