### ISSUE TITLE
Plugable USB3-HUB10-C2

### ISSUE THREAD

**Issue by tiaanmuller** [mvp/uhubctl#322]
Hello

Quick feedback on Plugable USB3-HUB10-C2

Uhubctl picks it up, but power switching only works on the two charge ports, not the normal ports.

I have a similar experience with the Plugable USB3-HUB7C, it also only supports power switching on the two charge ports, not the normal ports, you might want to update your list.

Although I know you say to only send you working ones, I really think having a list of "been tried, didn't work" would be beneficial, as I've had 10 different hubs now trying to find those that work. Some I would hope to work such as Startech's 7 port usb 3.0 hub, doesn't work (uhubctl picks it up, but no port switching works)  Not even all Amazonbasics work (although those on your list do, but they're not available to order anymore, none of them).

**Comment by mvp** [comment]
Thanks for you submission, readme updated!

Regarding maintaining list of unsupported devices - this is not really feasible. Such list would be huge, I don't have capacity to maintain it.
