### ISSUE TITLE
adding Amazon Basics U3-7HUB

### ISSUE THREAD

**Issue by greatjuan** [mvp/uhubctl#325]
7 port USB3.0 hub that has power control on only 1 port (fast charge marked)
ASIN: B07V4GJDLW
https://www.amazon.com/AmazonBasics-USB-7-Port-Adapter-White/dp/B07V4GJDLW

2 blue USB-A connectors (first with charge symbol) 5 white USB-A connectors
Turning off power affects only the first blue port with charge symbol

Current status for hub 1-1.1 [2109:0813 VIA Labs, Inc. USB3.0 Hub, USB 3.00, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 20-1.1 [2109:2813 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0503 power highspeed enable connect [1a40:0101 USB 2.0 Hub, USB 2.00, 4 ports, ganged]
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power

**Comment by mvp** [comment]
Thank you for reporting! Added note in  fb85325.

I assume it should work similarly on one charge port for U3-4HUB and U3-10HUB?
