### ISSUE TITLE
Power off not working

### ISSUE THREAD

**Issue by grykom** [mvp/uhubctl#327]
Hi, I have a problem with complete disconnection of power from a USB-connected Wemos Mini (arduino board) to my Raspberry Pi 4B 2GB

Setup:
- Raspberry Pi 4B (vid: 2109 and 1d6b)
- uhubctl version: 2.4.0-4-gfb853256

uhubctl

> Current status for hub 2 [1d6b:0003 Linux 5.4.79-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 3.00, 4 ports, ppps]
>   Port 1: 02a0 power 5gbps Rx.Detect
>   Port 2: 02a0 power 5gbps Rx.Detect
>   Port 3: 02a0 power 5gbps Rx.Detect
>   Port 4: 02a0 power 5gbps Rx.Detect
> Current status for hub 1-1 [2109:3431 USB2.0 Hub, USB 2.10, 4 ports, ppps]
>   Port 1: 0100 power
>   Port 2: 0100 power
>   Port 3: 0103 power enable connect [1a86:7523 USB2.0-Serial]
>   Port 4: 0100 power
> Current status for hub 1 [1d6b:0002 Linux 5.4.79-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 2.00, 1 ports, ppps]
>   Port 1: 0503 power highspeed enable connect [2109:3431 USB2.0 Hub, USB 2.10, 4 ports, ppps]

uhubctl -a off -p 3 -l 1-1
> Current status for hub 2 [1d6b:0003 Linux 5.4.79-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 3.00, 4 ports, ppps]
>   Port 3: 02a0 power 5gbps Rx.Detect
> Sent power off request
> New status for hub 2 [1d6b:0003 Linux 5.4.79-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 3.00, 4 ports, ppps]
>   Port 3: 0080 off
> Current status for hub 1-1 [2109:3431 USB2.0 Hub, USB 2.10, 4 ports, ppps]
>   Port 3: 0103 power enable connect [1a86:7523]
> Sent power off request
> New status for hub 1-1 [2109:3431 USB2.0 Hub, USB 2.10, 4 ports, ppps]
>   Port 3: 0000 off

status after:
> Current status for hub 2 [1d6b:0003 Linux 5.4.79-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 3.00, 4 ports, ppps]
>   Port 1: 02a0 power 5gbps Rx.Detect
>   Port 2: 02a0 power 5gbps Rx.Detect
>   Port 3: 0080 off
>   Port 4: 02a0 power 5gbps Rx.Detect
> Current status for hub 1-1 [2109:3431 USB2.0 Hub, USB 2.10, 4 ports, ppps]
>   Port 1: 0100 power
>   Port 2: 0100 power
>   Port 3: 0000 off
>   Port 4: 0100 power
> Current status for hub 1 [1d6b:0002 Linux 5.4.79-v7l+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 2.00, 1 ports, ppps]
>   Port 1: 0503 power highspeed enable connect [2109:3431 USB2.0 Hub, USB 2.10, 4 ports, ppps]

The voltage is still reaching Wemos (LED is on) so I tried the "USB devices are not removed after port power down on Linux" method:

> sudo udevadm trigger --action=remove /sys/bus/usb/devices/1-1.3/

and unfortunately there is no change - the voltage is still on.

Maybe i'm forgetting something? please give me a hint

**Comment by mvp** [comment]
This is FAQ: https://github.com/mvp/uhubctl#raspberry-pi-4b
RPi4B only supports turning power off for all ports at once:

    uhubctl -l 1-1 -a 0
