### ISSUE TITLE
use together with lsusb

### ISSUE THREAD

**Issue by m4us1ne** [mvp/uhubctl#338]
is it possible to use uhubcrk with bus id and device id?

**Comment by mvp** [comment]
No. lsusb device id changes every time device is connected/disconnected. When creating uhubctl, I really wanted to make sure that device is wouldn't change if device powered off then on. For that reason, I used current addressing scheme, which is different from lsusb, but very similar to one used in linux kernel: bus number followed by port numbers of hubs in chain, starting from root hub.
