### ISSUE TITLE
7-Port USB-2 Tripp-Lite U222-007-R  

### ISSUE THREAD

**Issue by CyberThunk** [mvp/uhubctl#345]
7-Port USB-2 Tripp-Lite U222-007-R  
4  of the 7 ports powered on and off with uhubctl on MacBook 12" Retina early 2015 running macOS 11.3.1. The 4 ports just above the power connector can be powered on and off using uhubctl.

**Comment by mvp** [comment]
Same question: test vbus off please. Thanks!

**Comment by mvp** [comment]
Closing as vbus control is not supported
