### ISSUE TITLE
Delock 62537 works

### ISSUE THREAD

**Issue by FauthD** [mvp/uhubctl#346]
Hi, 
this is a USB3 hub with 3 USB A and one USB C downstream ports.
Upstream has a short cable with USB C connector.

**Comment by FauthD** [comment]
Sorry, sent to fast.
here is the link to dealer:
https://www.delock.de/produkt/62537/merkmale.html?setLanguage=en

Many regards, Dieter Fauth

**Comment by mvp** [comment]
Can you please check if it supports turning VBUS off?

**Comment by FauthD** [comment]
Hi, 
sure it does. Otherwise I would not have written this report.
Checked with "charge doctors" and an WD USB drive. Its LED goes off as well.
A few other hubs I checked did not turn off vbus.
Also asked on support site of delock whether they know other models. Got a response, but he did not even understand my question. Will try to clarify.
Dieter

**Comment by mvp** [comment]
Thank you! Added to the list in f20007e.
