### ISSUE TITLE
Odroid-C4 compatibility

### ISSUE THREAD

**Issue by matwey** [mvp/uhubctl#348]
Hi,

Odroid-C4 SBC (https://www.hardkernel.com/shop/odroid-c4/) is equipped with onboard VIA USB Hub and works with uhubctl well. There is a limitation though. The power power is controlled only for port-pairs: both left and right pairs can be switched separately, but not the ports within the same double-connector.

**Comment by mvp** [comment]
Thanks for your report! Added to the list in 69c444b.
