### ISSUE TITLE
Manage non-hub USB-C port power?

### ISSUE THREAD

**Issue by xanoni** [mvp/uhubctl#350]
Hello everyone, I'm trying to power on/off the USB-C ports of a MacBook Pro 16" (2019, Big Sur 11.4). Does this tool allow me to do that? Do I even need a special tool?

I played around with uhubctl (2.4.0-12-g69c444b7), but it only showed me ports on USB hubs, but not the normal ports. Thank you.

**Comment by mvp** [comment]
`uhubctl` can work by enumerating USB hubs, and if they advertise per-port power switching, then it can control port power.

However, USB-C ports on Macbook Pro are somewhat weird. First off, they are primarily Thunderbolt ports, and USB support is their secondary function. Also, these ports are not explicitly attached to any USB hub. It makes these ports invisible for `uhubctl`.

If you have external USB hub that has USB-C ports, uhubctl should be able to enumerate them and control their port power.
