### ISSUE TITLE
Uhubctl works with the Lenovo Thinkpad X200 Ultrabase 

### ISSUE THREAD

**Issue by ixt** [mvp/uhubctl#36]
Please add to list of supported hubs

**Comment by mvp** [comment]
Can you please show uhubctl output? I'm looking for vid:pid of the hub in your laptop.

**Comment by mvp** [comment]
Also, can you provide exact model number? Is it [43R8781](http://amazon.com/dp/B001EVY5Y6)?

**Comment by ixt** [comment]
17ef:1005, 4 ports. 

ASM P/N: 44C0554. FRU P/N: 42X4963

**Comment by mvp** [comment]
Added in 5f95c92.
