### ISSUE TITLE
More hubs that may work

### ISSUE THREAD

**Issue by abrombo** [mvp/uhubctl#364]
I just install uhubctl on my Ubuntu 20.04 htpc.  Here are the results of running uhubctl -

sudo uhubctl
[sudo] password for brombo: 
Current status for hub 4-2 [0bda:0411 Generic 4-Port USB 3.0 Hub, USB 3.00, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 3-2 [0bda:5411 Generic 4-Port USB 2.0 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0103 power enable connect [1915:1001 123 COM Smart Control]
  Port 2: 0103 power enable connect [062a:4102 MOSART Semi. 2.4G Wireless Mouse]
  Port 3: 0103 power enable connect [04d8:fd08 Irdroid USB Infrared Transceiver 00000002]
  Port 4: 0103 power enable connect [062a:4101 MOSART Semi. 2.4G Keyboard Mouse]

the external hubs are:

https://smile.amazon.com/gp/product/B07L32B9C2/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1
and
https://smile.amazon.com/gp/product/B00BWF5U0M/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1 

What I do not understand is that I have all of my usb devices plugged into the usb 3 hub but uhubctl shows that they are plugged into a usb 2 hub.  Do you have any idea what is going on here?  Note if I plug a device into the external usb 2 hub it does not show up in the uhubctl printout like it does when plugged into the usb 3 hub.  Both external hubs are plugged into usb 3 outputs on the motherboard.

I have not yet tried using uhubctl to turn off/on the power to a port yet.  The reason I got uhubctl was that the irdroid device became disconnected if the pc was in sleep mode for too long and the only way I could get it to work was to unplug and plug it back in again.  Since connecting it to the external usb 3 hub this has not happened.

**Comment by mvp** [comment]
Read https://github.com/mvp/uhubctl#usb-30-duality-note. Most likely your end devices do not support USB3, and this show as connecting to USB2 compatibility virtual hub device.

Before adding new devices to supported list, we require that they support VBUS off. Please test that, e.g. try to turn power off to connected phone and confirm that it stops charging. Thanks!
