### ISSUE TITLE
HUB restart ON reboot

### ISSUE THREAD

**Issue by Micha854** [mvp/uhubctl#365]
I use the following hub:
RSHTech / Rosonway 16 port 100W hub

as soon as I restart the raspi, the usb ub restarts. is there a way to prevent this?

**Comment by mvp** [comment]
1. This does not seem to be related to uhubctl, so not really right place to ask.
2. Many hubs that implement USB properly actually do shutdown their port power upon losing connection to upstream host (e.g. host computer shutdown/reboot). So I think this is actually standards compliant behavior.
