### ISSUE TITLE
yubikey support on macbook 16"

### ISSUE THREAD

**Issue by georgettica** [mvp/uhubctl#372]
```
$ lsusb 2>/dev/null|  grep -i yubi
Bus XXX Device XXX: ID XXX XXX YubiKey OTP+FIDO+CCID
```
yet
```
$ sudo uhubctl | grep -i yub | wc -l
0
```

I am not sure what I am missing, and I though this script might do the trick but it does not https://github.com/georgettica/reset_usb

**Comment by mvp** [comment]
uhubctl will work on USB hubs that support per-port power switching.
Macbook Pro has 4 USB-C ports which are weird in their own - they are not exactly USB ports, but actually are Thunderbolt 3 ports which support USB3 in compatibility mode.
These ports do not seem to be connected to any actual USB hub, and this is why uhubctl cannot see them as USB ports.
If you connect any compatible USB hub to Macbook Pro USB-C port, and then plug yubikey to such hub, then uhubctl will work.
