### ISSUE TITLE
Support hub

### ISSUE THREAD

**Issue by xoocoon** [mvp/uhubctl#380]
Hi there, I successfully use usbhubctl with the following hub:
[03f0:2347 GenesysLogic USB3.1 Hub, USB 3.10, 4 ports, ppps]
on/off toggling works well on a per-port basis. This hub (chipset) is used in my HP monitor and also in my HP notebook.
Best regards, xoocoon

**Comment by mvp** [comment]
Genesis Logic chipser alone is not a guarantee that hub built using it will support power switching properly. Please check if VBUS off is actually supported by your hub(s) - quite often, it is not.

**Comment by mvp** [comment]
Please reopen if you have more information. We don't add generic chipsets into compatibility list.
