### ISSUE TITLE
USB Power Cycling Safety

### ISSUE THREAD

**Issue by KodeMunkie** [mvp/uhubctl#383]
On a RPI 4B I'm looking to power cycle a few LED lights rapidly (~10 on a sticky strip) to give the appearance of flickering lights.

Is there likely to be any issue with power cycling at least once a second that may cause hardware or software failures?

**Comment by mvp** [comment]
It shouldn't cause any issues that I'm aware of. There is even a project that used uhubctl to send Morse code messages (mentioned in README)

**Comment by KodeMunkie** [comment]
Thanks!
