### ISSUE TITLE
Control non-hub ports? 

### ISSUE THREAD

**Issue by spectromas** [mvp/uhubctl#385]
I'm looking for a way to control the power to a specific usb port (turn off on sleep, turn on at resume), is there a tool that can do this? I would use uhubctl as it works with the hub I have but unfortunately the usb device I want to control doesn't work very well through the hub.

**Comment by mvp** [comment]
uhubctl is designed to control power for hubs ports if they support per port power switching.
When it comes to sleep/resume behavior, this is typically controlled by your OS. Some people found inventive ways to hook up uhubctl invocation in sleep/resume scripts, but I don't know how to actually do that.

As for hub ports: any USB ports belong to some hub, possibly to onboard hub. Those onboard hubs may not support per port power switching, which would make them not suitable for uhubctl control. In these cases OS may or may not be able to turn power off during sleep. If OS cannot do it, nothing can - that is hardware limitation.
