### ISSUE TITLE
Hub clipset sleuthing

### ISSUE THREAD

**Issue by kenfehling** [mvp/uhubctl#395]
Hi, thanks so much for your work! I'm researching hubs and was wondering if it's possible to correlate the chipsets in already known working hubs with other hubs that use the same chipsets. For example, the Belkin F5U101 uses the Texas Instruments TUSB2046B, according to [this source](https://wikidevi.wi-cat.ru/index.php/Belkin_USB_Hubs), so that might bode well for the Belkin F5U021. Also the article from that site about the [DUB-H7](https://wikidevi.wi-cat.ru/D-Link_DUB-H7_rev_A2) is interesting. The chart at the bottom right shows the switch to the notorious Genesys GL850 in revisions B and C.

**Comment by mvp** [comment]
Unfortunately, that doesn't work. To the best of my knowledge, almost all USB chipsets do support per port power switching, and they allow OEMs to either enable or disable it. Bad news is that most manufacturers (OEMs) do not enable it.
Good news is that USB 3.2 standard requires hubs to have it enabled for USB-C ports. However, we still cannot quite find USB-C only hubs on a market.
