### ISSUE TITLE
Bytecc BT-UH340 - New revision no longer works

### ISSUE THREAD

**Issue by peterdey** [mvp/uhubctl#401]
Bought a Bytecc BT-UH340 from Amazon listing in #217 

New revision doesn't support PPPS.

```
New status for hub 2-1.5 [2109:2811 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports]
  Port 1: 0000 off
  Port 2: 0000 off
  Port 3: 0000 off
  Port 4: 0000 off

```
Tried on both USB3 and USB2-only ports with a USB lamp.
Tried both with and without supplied power adapter.

Unfortunately, neither the packaging nor the unit itself shows a revision number.

**Comment by mvp** [comment]
Thanks for reporting, added a warning.
