### ISSUE TITLE
can we add the street price with date, to the list of the usb hubs?

### ISSUE THREAD

**Issue by MaxPeal** [mvp/uhubctl#402]
can we add the street price with date, to the list of the usb hubs?
so its easier to find some working usb hub with out braking the bank :-)

**Comment by mvp** [comment]
Sorry, but answer is no - street prices change all the time, maintaining them is too much overhead.
Note that most hubs listed in supported table can be found on ebay for under $20. E.g. currently I see DLink DUB-H7 listed on ebay for $10.99 with free shipping.
