### ISSUE TITLE
Does M1 macbook air be supported?

### ISSUE THREAD

**Issue by FischLu** [mvp/uhubctl#403]
I have installed the uhubctl, but it doesn't work on my M1 macbook air which only has 2 usb-c ports. The outputs are
```
❯ uhubctl -f
No compatible devices detected!
Run with -h to get usage info.
```
Any help? Thank you

**Comment by mvp** [comment]
Macbook Air or Macbook Pro do not support per-port power switching for their USB-C ports.
Actually, these ports are not even true USB ports, they are rather Thunderbolt ports which happen to support USB connection in compatibility mode.
If you obtain any hub/device in supported devices list and plug it into your Macbook, uhubctl will work for downstream ports. E.g. for me it somehat works for USB-C Digital AV Multiport Adapter.
