### ISSUE TITLE
Plugable USB3-HUB7BC is a retired device

### ISSUE THREAD

**Issue by RodrigoKasama** [mvp/uhubctl#409]
In search for available HUB's, I made contact with the Plugable's support team and got informed that the [Plugable USB3-HUB7BC](https://plugable.com/products/usb3-hub7bc) is out of line. 
According to the suport team, the successor of this model is [Plugable USBC-HUB7BC](https://plugable.com/products/usbc-hub7bc) which you can choose either usb port types (USB or USB-C).

**Comment by mvp** [comment]
Thanks for reporting, but this hub is still available for sale on [Amazon](https://www.amazon.com/dp/B075NMVGP7).
Let's review this in couple years later, but so far this hub has its place in supported list.
