### ISSUE TITLE
HU9002V1EBL not properly turning ports off

### ISSUE THREAD

**Issue by bl4ckh4nd** [mvp/uhubctl#428]
Hi,

searched the issues already, but could not find a similar topic.

I own a Amazon HU9002V1EBL. Per port switching works like a charm except for the "Charging Ports (1-3)" where only data transfer is being cut as it seems, but not power. 

I tried a few options like -r 1000 already, but that does not seem to do the trick. Hub is connected via USB2 and power cable.

Am I missing something here or is there a solution to this?

Please let me know what is needed in terms of logs etc. to find the issue here.

**Comment by mvp** [comment]
1. Can you please try connecting it using USB3? You'll need USB3 host and compliant cable.
2. What kind of device is connected to your charging port? Does uhubctl show that power is off, but connected device continues to charge?

**Comment by mvp** [comment]
Added a note for this hub pointing to this very issue. Feel free to reopen if you have anything else to add @bl4ckh4nd - thanks!

**Comment by MrKevinWeiss** [comment]
Just to add a bit of data, I have the `‎HUC9002V1EBL` and had this issue with the type 3 USB connector (that it was shipped with), but switching the cable worked...  So I guess the cable matters.

**Comment by a-p-z** [comment]
Do you know what kind of cable made it working?

**Comment by MrKevinWeiss** [comment]
If you don't need speed you can just use a standard type B USB 2.0 cable.  That seems to be able to properly power it off.

<img width="439" height="367" alt="Image" src="https://github.com/user-attachments/assets/be10e0bc-6222-4f45-8a2f-8d29fbd0f3e3" />

**Comment by a-p-z** [comment]
Thanks for the quick answer!
I just tested one usb port and I confirm it works in this way.

But for my understanding, using the USB 2 cable, only the USB 2 controller will be connected to the bus and uhubctl does not have to manage both devices (USB2 and USB3) as described [here](https://github.com/mvp/uhubctl?tab=readme-ov-file#usb-30-duality-note).

Could the USB3/USB2 controller split is be the root cause? Power management commands sent to USB3 controller do not cut off the power?

```shell
# uhubctl with a USB2 cable
Current status for hub 1-5.4.4 [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
Current status for hub 1-5.4 [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0507 power highspeed suspend enable connect [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ppps]
Current status for hub 1-5 [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0507 power highspeed suspend enable connect [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ppps]
```

```shell
# uhubctl with a USB3 cable
Current status for hub 2-4.4.4 [2109:0817 VIA Labs, Inc. USB3.0 Hub, USB 3.20, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 2-4.4 [2109:0817 VIA Labs, Inc. USB3.0 Hub, USB 3.20, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 0203 power 5gbps U0 enable connect [2109:0817 VIA Labs, Inc. USB3.0 Hub, USB 3.20, 4 ports, ppps]
Current status for hub 2-4 [2109:0817 VIA Labs, Inc. USB3.0 Hub, USB 3.20, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 0203 power 5gbps U0 enable connect [2109:0817 VIA Labs, Inc. USB3.0 Hub, USB 3.20, 4 ports, ppps]
Current status for hub 1-5.4.4 [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
Current status for hub 1-5.4 [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0507 power highspeed suspend enable connect [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ppps]
Current status for hub 1-5 [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0507 power highspeed suspend enable connect [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ppps]
```

**Comment by MrKevinWeiss** [comment]
Might be a good question for @mvp
