### ISSUE TITLE
Getting Log floods when turning USB-Power off (Pi 4 B)

### ISSUE THREAD

**Issue by Stathogon** [mvp/uhubctl#430]
Hello, the Error that floods my Logs are 
`kernel: [22646073581] usb 1-1: clear tt 1 (9041) error -71`
this will quickly fill up my 80 mb log partition (5 mins).
Im running that on a 4 GB Pi 4 b and using this Command to controll the Power:
`sudo uhubctl -l 2 -a 0`
Any recommandation on what is going wrong?

**Comment by Stathogon** [comment]
Using eeprom version: 000138a1

**Comment by mvp** [comment]
I have also seen weird things happening when using bad USB cables - try using different cable.

**Comment by mvp** [comment]
Closing by timeout after one week. Please reopen if you have anything to add.
Seems like this is your local issue - no one else reported it before, please provide more details if you can reliably reproduce it on more than one RPi4 sample.
