### ISSUE TITLE
Bootloop on reboot (conditional)

### ISSUE THREAD

**Issue by crjase** [mvp/uhubctl#462]
`To reproduce:` **system**:raspberrypi-4B

1. Plug in some random cable that isn't supported, that's connected to strip-led's (custom made light, I soldered the cable)
2. Install nginx, run it and kill it with SIGTERM.
3. systemctl reboot as root
4. Congratulations, you've got yourself a boot loop. You can exit it by removing anything plugged into the pi, turning it off and back on after the capacitors have emptied on the pi.

Also, I didn't try to reproduce this again, I'm too tired to think much. The quality of this text is already bad because I can't think that good when I'm tired. Thanks in advance, I hope you manage to fix this soon.

**Comment by mvp** [comment]
This report doesn't seem to have anything to do with uhubctl. If anything, you should report this to Raspberry Pi foundation.
