### ISSUE TITLE
Acroname USB 2x4 - Should be supportable

### ISSUE THREAD

**Issue by tuctboh** [mvp/uhubctl#463]
Hi,

root@valhalla-v1:/usr/local/src/uhubctl# lsusb      
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 028: ID 24ff:0011 Acroname Inc. USBHub2x4 BS
Bus 001 Device 027: ID 24ff:8011 Acroname Inc. 
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

root@valhalla-v1:/usr/local/src/uhubctl# ./uhubctl 
Current status for hub 2 [1d6b:0003 Linux 5.15.56-v8+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 3.00, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 0080 off
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 1-1.2 [24ff:8011 Acroname, USB 2.00, 5 ports, ppps]
  Port 1: 0103 power enable connect [24ff:0011 Acroname Inc. USBHub2x4 BS E2C9BFA6]
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
  Port 5: 0100 power
Current status for hub 1-1 [2109:3431 USB2.0 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0503 power highspeed enable connect [24ff:8011 Acroname, USB 2.00, 5 ports, ppps]
  Port 3: 0100 power
  Port 4: 0100 power
Current status for hub 1 [1d6b:0002 Linux 5.15.56-v8+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 2.00, 1 ports, ppps]
  Port 1: 0503 power highspeed enable connect [2109:3431 USB2.0 Hub, USB 2.10, 4 ports, ppps]

Bus 001 Device 028: ID 24ff:0011 Acroname Inc. USBHub2x4 BS
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        32
  idVendor           0x24ff Acroname Inc.
  idProduct          0x0011 
  bcdDevice            1.03
  iManufacturer           2 Acroname Inc.
  iProduct                3 USBHub2x4 BS
  iSerial                 1 E2C9BFA6
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0020
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xc0
      Self Powered
    MaxPower              100mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass    136 
      bInterfaceProtocol     16 
      iInterface              4 Link
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0020  1x 32 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0020  1x 32 bytes
        bInterval               0
Device Status:     0x0001
  Self Powered

Bus 001 Device 027: ID 24ff:8011 Acroname Inc. 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 
  bDeviceProtocol         1 Single TT
  bMaxPacketSize0        64
  idVendor           0x24ff Acroname Inc.
  idProduct          0x8011 
  bcdDevice            1.00
  iManufacturer           1 Acroname
  iProduct                2 
  iSerial                 3 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength       0x0019
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                2mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         9 Hub
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 Full speed (or root) hub
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0001  1x 1 bytes
        bInterval              12
Hub Descriptor:
  bLength               9
  bDescriptorType      41
  nNbrPorts             5
  wHubCharacteristic 0x008d
    Per-port power switching
    Compound device
    Per-port overcurrent protection
    TT think time 8 FS bits
    Port indicators
  bPwrOn2PwrGood       50 * 2 milli seconds
  bHubContrCurrent      1 milli Ampere
  DeviceRemovable    0x02
  PortPwrCtrlMask    0xff
 Hub Port Status:
   Port 1: 0000.0103 power enable connect
   Port 2: 0000.0100 power
   Port 3: 0000.0100 power
   Port 4: 0000.0100 power
   Port 5: 0000.0100 power
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            9 Hub
  bDeviceSubClass         0 
  bDeviceProtocol         0 Full speed (or root) hub
  bMaxPacketSize0        64
  bNumConfigurations      1
Device Status:     0x0001
  Self Powered

The unit has its own CLI -

root@valhalla-v1:/usr/local/src/brainstem-2.9.16/bin# ./AcronameHubCLI -v 0
Arguments: ./AcronameHubCLI -v 0 
Sucessfully connected to USBHub2x4 SN: 0xE2C9BFA6
Active Upstream: 0
Port VBUS HS
   0    1  0
   1    1  0
   2    1  0
   3    1  0

and using their tool, I can turn things off, like #3 .

root@valhalla-v1:/usr/local/src/brainstem-2.9.16/bin# ./AcronameHubCLI --ports 3 --enable 0
Arguments: ./AcronameHubCLI --ports 3 --enable 0 
Sucessfully connected to USBHub2x4 SN: 0xE2C9BFA6
Port: 3 was sucessfully disabled

root@valhalla-v1:/usr/local/src/brainstem-2.9.16/bin# ./AcronameHubCLI -v 0
Arguments: ./AcronameHubCLI -v 0 
Sucessfully connected to USBHub2x4 SN: 0xE2C9BFA6
Active Upstream: 0
Port VBUS HS
   0    1  0
   1    1  0
   2    1  0
   3    0  0

but it seems like uhubctl doesn't realize -

root@valhalla-v1:/usr/local/src/uhubctl# ./uhubctl   
Current status for hub 2 [1d6b:0003 Linux 5.15.56-v8+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 3.00, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 0080 off
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 1-1.2 [24ff:8011 Acroname, USB 2.00, 5 ports, ppps]
  Port 1: 0103 power enable connect [24ff:0011 Acroname Inc. USBHub2x4 BS E2C9BFA6]
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
  Port 5: 0100 power
Current status for hub 1-1 [2109:3431 USB2.0 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0503 power highspeed enable connect [24ff:8011 Acroname, USB 2.00, 5 ports, ppps]
  Port 3: 0100 power
  Port 4: 0100 power
Current status for hub 1 [1d6b:0002 Linux 5.15.56-v8+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 2.00, 1 ports, ppps]
  Port 1: 0503 power highspeed enable connect [2109:3431 USB2.0 Hub, USB 2.10, 4 ports, ppps]

Thanks, Tuc

**Comment by mvp** [comment]
For whatever reason Acroname doesn't support switching power as specified in USB 2.0 standard - not much we can do here.

Acroname is using their own protocol to control power on their hubs. I wouldn't mind implementing it in uhubctl, but as far as I know they don't provide any details how it works.
Long story short, this should be addressed by Acroname.
