### ISSUE TITLE
Lamp will not turn off no matter what

### ISSUE THREAD

**Issue by caffeine01** [mvp/uhubctl#466]
I have a basic ikea "HÅRTE" usb lamp and i want to be able to automate it with a raspberry pi 4B. But no matter which port I turn off, it stays on. Any ideas????

I have the latest versions of everything and another important thing to note is that i use a sandisk usb for storage and not an SD card.

Potentially i could turn off just the usb 2 hubs but i need the usb 3 ones to stay on.

**Comment by mvp** [comment]
As explained in FAQ, Raspberry Pi has hardware limitation: https://github.com/mvp/uhubctl#raspberry-pi-turns-power-off-on-all-ports-not-just-the-one-i-specified
You have to turn off all hub ports: 
```
uhubctl -l 2 -a 0
```
Note - do make sure you use uhubctl 2.4.0 or later. Any previous version will not work correctly for RPi4.
