### ISSUE TITLE
Feature request: support for rock 5b

### ISSUE THREAD

**Issue by qqice** [mvp/uhubctl#470]
Will there be a way to add support for rock 5b? If so, what can I do for the development?

**Comment by mvp** [comment]
Not really. All that is necessary to make it work on any USB hardware is to have such hardware advertise power switching and actually implement transistors to turn power off.

All USB chipset vendors support this, but allow OEMs (original equipment manufacturers) to enable or disable such descriptor at chipset level.

If you are a developer/manufacturer of rock 5b, then you may have capacity to make it happen. If not, forget about it.
