### ISSUE TITLE
TP-LINK UH720

### ISSUE THREAD

**Issue by KKuzmichev** [mvp/uhubctl#483]
TP-LINK UH720 work fine with uhubctl
Tested on OSX 13.1
Info:
Ports: 7
USB: 3.2
Chipset: RTS5411

P.S.
UH700 should work too

**Comment by mvp** [comment]
Unfortunately it was shown in #133 that UH700 doesn't support vbus off properly.

Given that, we need to thoroughly test UH720 for vbus control. Please check that voltage gets cut on power off - that is connected USB fan or light turns off, or connected phone stops charging. Thanks!

**Comment by KKuzmichev** [comment]
Ohh(
Still power on port like on UH700
Sorry
