### ISSUE TITLE
Add list of tested USB hubs that does not work

### ISSUE THREAD

**Issue by Decee1** [mvp/uhubctl#494]
Hello,
Is it possible to also add a file with USB hubs that was tested and didn't work?
In my case i need USB hubs externally powered that support this feature. 
It should not be a list just like the "supported hubs" list but rather just a link to a file as the file can get quiet big.

**Comment by mvp** [comment]
Unfortunately answer is no. Majority of the hubs do not support this - I cannot boil the ocean.

Instead, we support list of hubs that do work.
