### ISSUE TITLE
Library works perfect with StarTech.com USB-Hub (HB30A4AIB)

### ISSUE THREAD

**Issue by Gracying** [mvp/uhubctl#497]
Just installed uhubctl and tried it for my USB Hub, switching power off and on per-port works as desired.

USB- Hub : Startech USB-A Hub [Model No. HB30A4AIB]
uhubctl Model Output: [2109:2817 VIA Labs, Inc. USB2.0 Hub, USB 2.10, 4 ports, ppps]

Thank you for providing this awesome free library!

**Comment by mvp** [comment]
I have Startech USB 3 hub too (maybe not this exact model), and it doesn't support vbus off, so I didn't add it to the table. Please check if your hub actually supports cutting power off per FAQ. Thanks!

**Comment by mvp** [comment]
Thanks, I will add it then!
