### ISSUE TITLE
atolla usb3.0 hub cannot power down

### ISSUE THREAD

**Issue by raghugit-corp** [mvp/uhubctl#500]
uhubctl detects the hub, but unable to power off the ports.

[rj@desk11 uhubctl-master]$
[rj@desk11 uhubctl-master]$sudo ./uhubctl
[sudo] password for rj:
Current status for hub 2-8.1 [045b:0210, USB 3.00, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 2-8 [045b:0210, USB 3.00, 4 ports, ppps]
  Port 1: 0263 power 5gbps U3 enable connect [045b:0210, USB 3.00, 4 ports, ppps]
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 0203 power 5gbps U0 enable connect [2833:0186 Oculus sorrento dev a4ebaf24]
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 1-11.1 [045b:0209, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0503 power highspeed enable connect [0403:6011 FTDI P2NFF_APDEV FT7I37OZ]
  Port 3: 0100 power
  Port 4: 0100 power
Current status for hub 1-11 [045b:0209, USB 2.10, 4 ports, ppps]
  Port 1: 0503 power highspeed enable connect [045b:0209, USB 2.10, 4 ports, ppps]
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
[rj@desk11 uhubctl-master]$
[rj@desk11 uhubctl-master]$ sudo ./uhubctl  -a off -p 3 -l 2-8
Current status for hub 2-8 [045b:0210, USB 3.00, 4 ports, ppps]
  Port 3: 0203 power 5gbps U0 enable connect [2833:0186 Oculus sorrento dev a4ebaf24]
Sent power off request
New status for hub 2-8 [045b:0210, USB 3.00, 4 ports, ppps]
  Port 3: 00a0 off
Current status for hub 1-11 [045b:0209, USB 2.10, 4 ports, ppps]
  Port 3: 0100 power
Sent power off request
New status for hub 1-11 [045b:0209, USB 2.10, 4 ports, ppps]
  Port 3: 0000 off

=== device is still detected after off ====
[rj@desk11 uhubctl-master]$ adb devices
List of devices attached
12356ebefxx	device

[rj@desk11 uhubctl-master]$
[rj@desk11 uhubctl-master]$ sudo ./uhubctl  -a on -p 3 -l 2-8
Current status for hub 2-8 [045b:0210, USB 3.00, 4 ports, ppps]
  Port 3: 00a0 off
Sent power on request
New status for hub 2-8 [045b:0210, USB 3.00, 4 ports, ppps]
  Port 3: 02a0 power 5gbps Rx.Detect
Current status for hub 1-11 [045b:0209, USB 2.10, 4 ports, ppps]
  Port 3: 0000 off
Sent power on request
New status for hub 1-11 [045b:0209, USB 2.10, 4 ports, ppps]
  Port 3: 0100 power

[rj@desk11 uhubctl-master]$ adb devices
List of devices attached
12356ebefxx	device

[rj@desk11 uhubctl-master]$

Below is lsusb -v

Hub Descriptor:
  bLength              12
  bDescriptorType      42
  nNbrPorts             4
  wHubCharacteristic 0x0009
    Per-port power switching
    Per-port overcurrent protection
  bPwrOn2PwrGood       50 * 2 milli seconds
  bHubContrCurrent    200 milli Ampere
  bHubDecLat          0.1 micro seconds
  wHubDelay           705 nano seconds
  DeviceRemovable    0x00
 Hub Port Status:
   Port 1: 0000.0203 5Gbps power U0 enable connect
   Port 2: 0000.02a0 5Gbps power Rx.Detect
   Port 3: 0000.02a0 5Gbps power Rx.Detect
   Port 4: 0000.02a0 5Gbps power Rx.Detect

**Comment by mvp** [comment]
It simply means that your hub does not really support cutting power at hardware level.

Hubs listed in supported table all should work. Any other hubs may work, but there is no guarantee - hub manufacturers like to save few cents of installing few transistors.
