### ISSUE TITLE
Python wrapper

### ISSUE THREAD

**Issue by YanBC** [mvp/uhubctl#501]
Hi there, is it possible to make a python wrapper for `uhubctl`?

**Comment by mvp** [comment]
I believe few of them already exist, e.g. `python3-uhubctl`, `pyhubctl` - both require `uhubctl` binary installed and present in `PATH`.

However, I cannot really recommend one over another. It if was me, I would probably write yet another one. For all I know, most python projects simply use subprocess call with `uhubctl` and providing proper parameters.
