### ISSUE TITLE
ExSys EX-1113HMS does not support VBUS off

### ISSUE THREAD

**Issue by mvp** [mvp/uhubctl#502]
_Originally posted by @slk9 in https://github.com/mvp/uhubctl/discussions/427#discussioncomment-5533911_

I have tried ExSys EX-1113HMS today on MacOS. It does not work as expected.
Yes uhubctl will cut the connectivity so no communication from host to device connected and ports reported as off.
But all ports still provide voltage and current to devices connected. Which makes ExSys EX-1113HMS useless for most usecases when we need uhubctl.

**Comment by mvp** [comment]
@slk9, thanks for reporting this. I will remove this hub from supported list

**Comment by F7Patrick** [comment]
Hi,

ExSys EX-1113HMS works for me under Linux with USB 2.0.
USB 3.0 doesn't work.

BR Patrick
