### ISSUE TITLE
LAN9512 support

### ISSUE THREAD

**Issue by bensukys** [mvp/uhubctl#505]
Just tested the Microchip EVB9512 board and it supports individual port power control: https://www.digikey.com/en/products/detail/microchip-technology/EVB9512/2166045

**Comment by SlySven** [comment]
Well, the LAN9512 chip is what older RPis use - so it is not surprising that there is some claim of functionality by that - and given that you are talking about an "evaluation" board it wouldn't be unreasonable for it to actually have the components to do the power switching.

As people who monitor this project well know though, the silicon in the integrated circuits of hubs very often support the functionality that even older USB specifications suggest if not demand; the trouble is the manufacturers of hardware (often based in the Far-East) who shave off fractions of the local currency of your choice by leaving off things that don't appear to impede the use of their unit by the majority of *typical* users...

Anyhow, I am going to beat @mvp to the punch (:grinning: ) and ask:  does this ***not inexpensive*** unit actually switch the VBus power off on the ports when you tell it to? Does a USB fan or light actually go off when the unit claims it has removed the power from the port?

**Comment by bensukys** [comment]
Ah, sorry forgot to include that information. Yes, it includes a MIC2026 load switch and I verified with a DMM that VBUS is actually switched off.
