### ISSUE TITLE
2 USB devices support PPPS but they don't turn off power as expected

### ISSUE THREAD

**Issue by davidhuziji** [mvp/uhubctl#507]
Hello! Thanks a lot for developing this helpful tool.
I find out that 2 USB devices can support PPPS but it doesn't take effect as I expected.

These 2 USB devices are
- [Lenovo LDA-KP USB doc](https://www.lenovo.com/us/en/p/accessories-and-software/docking/docking_usb-docks-(universal-cable-docks)/40ay0090us)
- UGREEN CM212 USB hub

I connected my physical boards to those hubs. USB ports on these physical boards are used for both power input and serial port data output.
When I use uhubctl to turn off the port power, serial port via USB port does be turned off.
However, the physical board is still running and all LEDs are still ON as well. It looks like the turn off operation doesn't fully take effect.

May I know if I missed anything? Can you please give me some help to fully turn off the power to USB port?

**Comment by mvp** [comment]
Unfortunately, device advertising PPPS support doesn't mean that it actually supports turning voltage off to USB port. This is why we maintain table of tested devices which actually do that (vbus off).

This is not issue with uhubctl, but rather with your hardware not working properly.
