### ISSUE TITLE
StarTech hub with different USB ID doesn't work

### ISSUE THREAD

**Issue by mkohler** [mvp/uhubctl#509]
I just bought a StarTech HB30A4AIB, which is a model listed on the README. However, this hub has USB ID `14b0:01ef`, which is different than the ID of the HB30A4AIB in the README. I tested this hub, and while it does report that it turned off the power on a port, it doesn't actually turn off the power.

I contacted StarTech and they said the change is likely due to changing chipsets.
> We've indeed had a chipset change in 2022: changing from the VL817 B0 to the VL817 C0, as per Via Labs changes have been made to core logic and physical layers, most of these are meant to improve USB-IF compliance.

**Comment by mvp** [comment]
That's pretty funny - break per port power switching to improve USB-IF compliance 🤣.
I will add a readme note to this issue tomorrow, thanks for reporting!

**Comment by daler-rahimov** [comment]
@mvp you have a wrong VID:PID in the README file for the warning, `2109:2817` instead of `14b0:01ef`

**Comment by mvp** [comment]
This is quite common situation. USB vendor 2109 is Via Labs, Inc - company that manufactures USB chipsets. 14b0 is Startech Inc (hub manufacturer). Many hub manufacturers start by using USB chipset unconfigured and by default having identity of chipset maker. Over time, they may pay small fee to USB IF to obtain their custom vendor id and configure USB chipset to carry that id.

**Comment by colorimeter** [comment]
Maybe a firmware update resolves the issue https://wiki.odroid.com/odroid-c4/software/vl817_usb-hub_fw_update
