### ISSUE TITLE
Add Version number / release with version

### ISSUE THREAD

**Issue by damadmai** [mvp/uhubctl#51]
Could you please add a git tag for the current version & make a release?

I would want to package your program for a linux distribution which only accepts packages that have a version number. (Maybe 1.8.0 - You currently have a C define for that)

Thanks

**Comment by mvp** [comment]
Yes, I wanted to do this for long time. I will take a look at it over this weekend.

**Comment by mvp** [comment]
Done! Thanks for raising this issue.
