### ISSUE TITLE
Brazilian iPlace USB hub help

### ISSUE THREAD

**Issue by retpolanne** [mvp/uhubctl#515]
Hey! I'm testing a hub from iPlace (a Brazilian Apple reseller) and it seems to support PPPS. However, I can only shut down some specific devices with it.

https://www.iplace.com.br/adaptador-multiportas-usb-usbc-hdmi-rj45-iplace/222942?gclid=EAIaIQobChMImuLd1JaOgAMV0kFIAB1GBQF8EAQYASABEgKCIvD_BwE

I noticed that it has the same problem as https://github.com/mvp/uhubctl/issues/361 for reporting 5 USB-3 but 4 USB-2. 

Tested with the CP2012 UART to USB adapter – GND light turns off when I toggle it off. 

Tested with the Apple Watch charger – when I turn it off, it doesn't stop charging. However, when I turn it on again, it stops charging for a second and then resumes. 

I don't have lsusb right now, but these are the two devices: 

```
╰→ uhubctl -l 2-1 -e
Current status for hub 2-1 [0bda:5411 Generic USB2.1 Hub, USB 2.10, 5 ports, ppps]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
  Port 5: 0100 power
  
  Current status for hub 2-2 [0bda:0411 Generic USB3.2 Hub, USB 3.20, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 0203 power 5gbps U0 enable connect [0b95:1790 ASIX AX88179A 000000000010F3]
  Port 4: 02a0 power 5gbps Rx.Detect

```

**Comment by mvp** [comment]
Too many red flags to add this to supported list.
Anything that requires custom overrides like -e is just not worth recommending, not to mention that power control doesn't seem to actually cut vbus. But thanks for reporting!
