### ISSUE TITLE
Possibility to configure USB port power

### ISSUE THREAD

**Issue by hursevich** [mvp/uhubctl#53]
I would like to configure USB port power to allow Android device to be visible by ADB but not charging.

**Comment by mvp** [comment]
You can use uhubctl to disable power, but you will also lose data connection. Data connection that is used by adb absolutely requires USB power to be active.

On dome buggy hubs, even if uhubctl reports port power off, it might actually disable only data connection, but hub would still keep providing the power to the port.

If you want device to stop drawing USB power, some devices actually allow maximum charge current to be configured using custom sysfs entries - you will need to know which sysfs entry to tweak, and of course you must have root permissions, which is typically not possible on unrooted devices.
