### ISSUE TITLE
No compatible devices detected!

### ISSUE THREAD

**Issue by BytEvil** [mvp/uhubctl#532]
Hi. No compatible devices detected!.

```
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

Version 2.5.0/Khadas Vim3 board

Thanks ;)

**Comment by mvp** [comment]
Sorry, but I don't understand how you expect to be fixed. If your USB hubs do not advertise power switching support, there is nothing uhubctl can do to make it work.
