### ISSUE TITLE
Chieftec CRD-901H

### ISSUE THREAD

**Issue by bobosch** [mvp/uhubctl#548]
https://www.chieftec.eu/products-detail/de/342/CRD-901H
works with uhubctl without power switching (my mobile phone charges without data connection after switching to off)

Current status for hub 2-3 [05e3:0620 GenesysLogic USB3.2 Hub, USB 3.20, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 1-3 [05e3:0610 GenesysLogic USB2.1 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power

It helped me with OpenSuperClone to reset the USB connection

**Comment by mvp** [comment]
Thanks for your report! Since this hub doesn't support vbus off, we cannot add it to supported table.
