### ISSUE TITLE
RSHTECH 7-Port USB 3.0 Hub RSH-A37S - Working but no VBUS control

### ISSUE THREAD

**Issue by harrisja821** [mvp/uhubctl#549]
Bought this from Amazon UK ([https://www.amazon.co.uk/dp/B083QJ87JJ]) works in uhubctl but does NOT kill the VBUS. Tried connected to both a USB2.0 and USB3.0 port on host machine, no joy. Tested using USB light (for VBUS testing) and USB keyboard (for USB data testing).

Reports USB 2.1 hub as 0bda:5411 and USB3.2 hub as 0bda:0411.

**Comment by mvp** [comment]
Thanks for reporting! However, since this hub doesn't support vbus control, we can't add it to supported table.
