### ISSUE TITLE
TP-Link UH700 - Works - Needs -r 1000 for Linux 5.xx

### ISSUE THREAD

**Issue by gam3** [mvp/uhubctl#555]
Uses the Realtek chipset 0bda:0411, 0bda:5411.

Works with no issues on Linux 6.xx

Needs -r 1000 (or a little less) for Linux 5.xx

Current status for hub 2-1.1 [0bda:0411 Generic USB3.2 Hub, USB 3.20, 4 ports, ppps]
Current status for hub 2-1 [0bda:0411 Generic USB3.2 Hub, USB 3.20, 4 ports, ppps]
Current status for hub 1-2.1 [0bda:5411 Generic USB2.1 Hub, USB 2.10, 4 ports, ppps]
Current status for hub 1-2 [0bda:5411 Generic USB2.1 Hub, USB 2.10, 4 ports, ppps]

Ran on Debian (Kernel 6.1.0) and OpenWRT ( 5.15.139)

Bus 002 Device 088: ID 0bda:0411 Generic USB3.2 Hub
Bus 002 Device 016: ID 0bda:0411 Generic USB3.2 Hub
Bus 001 Device 017: ID 0bda:5411 Generic USB2.1 Hub
Bus 001 Device 002: ID 0bda:5411 Generic USB2.1 Hub

**Comment by mvp** [comment]
We had this hub tested before multiple times e.g. #133 - it doesn't support vbus control.
