### ISSUE TITLE
Supported hardware: Asus ROG Crosshair X670E Hero

### ISSUE THREAD

**Issue by fpoto** [mvp/uhubctl#556]
Motherboard Asus ROG Crosshair X670E Hero.
```
# uhubctl
Current status for hub 6-5 [174c:3074 ASUS TEK. ASM107x, USB 3.00, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 5-5 [174c:2074 ASUS TEK. ASM107x, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0503 power highspeed enable connect [058f:6387 Generic Mass Storage 83F6ED99]
  Port 3: 0100 power
  Port 4: 0100 power
```
This is a single hub detected as two hubs. Switching port 2 off and on works, as I see that the led on the memory key switches off and on.

Unfortunately, if I connect a fan to the port, it works even after off.

**Comment by mvp** [comment]
Sorry, since vbus control is not supported, we cannot add this to supported table. But thanks for reporting! Please report any other unlisted hub that supports vbus @fpoto!
