### ISSUE TITLE
Cyberpower CP-H420P Incorrectly on approved list

### ISSUE THREAD

**Issue by andyaprwx** [mvp/uhubctl#557]
I bought the Cyberpower CP-H420P because it's in the list of confirmed to work devices.
However, I plugged in a fan and a little stick heater as well as a USB thumb drive, and it would not power off the fan & heater, only the USB data connection. Therefore, I don't think this actually works, as I believe the list is supposed to include VBUS power.

![uhubctl](https://github.com/mvp/uhubctl/assets/67767712/0912af18-2049-4fce-810c-6d2ac1460823)

**Comment by mvp** [comment]
Thanks for your report, removed non-compliant device.
