### ISSUE TITLE
Supported hardware: RSHTECH RSH-A10

### ISSUE THREAD

**Issue by neolao** [mvp/uhubctl#568]
| Manufacturer | Product | Ports | USB | VID:PID | Release | EOL |
| - | - | - | - | - | - | - |
| RSHTECH | RSH-A10 | 10 | 3.0 | 2109:2822 | ? | |

We can turn on/off each port individually. It also turns the LED on/off.

**Comment by hmaerki** [comment]
Hi @neolao 

I have a RSH-A10 on my deks which uses these chips: `0bda:0411 Realtek Semiconductor Corp. Hub`. See my pull request https://github.com/mvp/uhubctl/pull/567/files and https://github.com/octoprobe/pyhubctl/blob/main/usb_hubs/README_RSHTECH_RSH-A10.md.

Could you please add the outut of `uhubctl` and `sudo lsusb -v`.

**Comment by mvp** [comment]
This was added in #567
