### ISSUE TITLE
Turn off power just to usb

### ISSUE THREAD

**Issue by NourSoltani** [mvp/uhubctl#569]
Greetings,
I hope you are doing well.
Can I turn off the power going to the USB ports, while keeping the ethernet port working??

**Comment by mvp** [comment]
I assume you meant Raspberry Pi? To the best of my knowledge, Raspberry Pi 2 and 3 have ethernet power controlled by port 1 and USB ports power is controlled by port 2 - as long as you leave port 1 undisturbed and con, ethernet will continue to work.
Rasberry Pi 4 and 5 have separate power rail for ethernet not related to USB, and it should work regardless of USB power state.
