### ISSUE TITLE
D-link How to get the rev ?

### ISSUE THREAD

**Issue by mrdotb** [mvp/uhubctl#573]
Is it possible to get the rev of D-link based on the packaging ?
If not what is the way to get the rev ?

**Comment by mrdotb** [comment]
![image](https://github.com/mvp/uhubctl/assets/7212914/37821846-bd39-4aab-920e-e4f1d1b31b11)

Is D1 is the same as DUB-H7 rev D ?

**Comment by mrdotb** [comment]
![4165c631-3b86-11ef-98ef-db477704a068](https://github.com/mvp/uhubctl/assets/7212914/cd56dc4c-7001-4540-ab4c-722a27028095)
Find another one seems to be DUB-H7 rev A (silver)

**Comment by mvp** [comment]
Get silver one, it would definitely work. Black versions are hot or miss when it comes to power switching

**Comment by mrdotb** [comment]
Thanks for the answer I will get the silver one.
