### ISSUE TITLE
Supported hardware: Sabrent HB-BU10

### ISSUE THREAD

**Issue by AlfredoSequeida** [mvp/uhubctl#576]
output of uhubctl

```
Current status for hub 2-1.4.4 [0bda:0411 Generic USB3.2 Hub, USB 3.20, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 2-1.4 [0bda:0411 Generic USB3.2 Hub, USB 3.20, 4 ports, ppps]
  Port 1: 02a0 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 0263 power 5gbps U3 enable connect [0bda:0411 Generic USB3.2 Hub, USB 3.20, 4 ports, ppps]
Current status for hub 2-1 [0bda:0411 Generic USB3.2 Hub, USB 3.20, 4 ports, ppps]
  Port 1: 02e0 power 5gbps Polling
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 0263 power 5gbps U3 enable connect [0bda:0411 Generic USB3.2 Hub, USB 3.20, 4 ports, ppps]
Current status for hub 1-1.4.4 [0bda:5411 Generic USB2.1 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
Current status for hub 1-1.4 [0bda:5411 Generic USB2.1 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0507 power highspeed suspend enable connect [0bda:5411 Generic USB2.1 Hub, USB 2.10, 4 ports, ppps]
Current status for hub 1-1 [0bda:5411 Generic USB2.1 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0503 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0507 power highspeed suspend enable connect [0bda:5411 Generic USB2.1 Hub, USB 2.10, 4 ports, ppps]
```

Product page: https://sabrent.com/products/HB-BU10
10 ports, USB 3.2, switches on usb hub have to remain in the on position.

Note: VBUS working is undetermined (depending on the device plugged in). When testing, I plugged in a Pixel 3XL and switching a port off DOES stop the device from charging. However, plugging in a Galaxy S8 Plus and turning a port off DOES NOT stop the device from charging. Using the [Ampere application,](https://play.google.com/store/apps/details?id=com.gombosdev.ampere&hl=en_US) it looks like what is happening here is the port drops amps to between 10 and 20 mA when switched off and periodically increases/decreases. So my guess is that the Pixel 3XL decides this is too low and stops charging while the Galaxy s8 Plus decides the phone is charging, but at a very low amp rate. I am not sure if this is the expected behavior for VBUS. Additionally, this also explains why the Pixel 3XL does not stop charging right away after switching a port off. It takes a few seconds while the amps are dropping until the amps drop low enough that the charge controller decides to stop charging the battery.

**Comment by mvp** [comment]
1. According to https://sabrent.com/products/HB-BU10, max supported speed is 5Gbps, which corresponds to USB 3.0 not 3.2 (see #447).

2. Since this hub vbus behavior is not 100% reliable - seems like there is some trickle current even when port is off, I would err on a side of not including it to supported table.
