### ISSUE TITLE
RPI4B + Inateck HB2025A - cannot power off

### ISSUE THREAD

**Issue by Matsuo3rd** [mvp/uhubctl#589]
Hello,

I cannot get RPI4b + Inateck HB2025A switching off ports. I purchased HB2025A knowing that RPI4 ports are ganged. I plugged HB2025A on USB 2 RPI port (following guidance from https://github.com/mvp/uhubctl/issues/451). I plugged the USB device (a Sony gamepad) on hub's port 2 (following guidance from aforementioned link).

`sudo uhubctl -a off -l 1-1.3 -p 2`
Does not power off the port

However performing a power off on RPI4 USB port hosting HB2025A hub **before** make subsequent calls powering the USB device work.

So the following sequence works:
```
sudo uhubctl -l 1-1 -a cycle
sudo uhubctl -a off -l 1-1.3 -p 2
```

... but this resets my whole USB chain which I am not happy with (others USB devices plugged in).

Some context:

```
uhubctl -v
2.6.0-4-ge0d1c34e

uname -a
Linux rpi4 6.6.51-v8+ #1796 SMP PREEMPT Fri Sep 13 14:38:11 BST 2024 aarch64 GNU/Linux

sudo rpi-eeprom-update
BOOTLOADER: up to date
   CURRENT: Wed 11 Jan 17:40:52 UTC 2023 (1673458852)
    LATEST: Wed 11 Jan 17:40:52 UTC 2023 (1673458852)

sudo uhubctl -f
Current status for hub 2 [1d6b:0003 Linux 6.6.51-v8+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 3.00, 4 ports, ppps]
  Port 1: 0203 power 5gbps Rx.Detect
  Port 2: 02a0 power 5gbps Rx.Detect
  Port 3: 02a0 power 5gbps Rx.Detect
  Port 4: 02a0 power 5gbps Rx.Detect
Current status for hub 1-1.3 [2109:2822 VIA Labs, Inc. USB2.0 Hub 000000001, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0103 power enable connect [054c:09cc Sony Interactive Entertainment Wireless Controller]
  Port 3: 0103 power
  Port 4: 0100 power
Current status for hub 1-1 [2109:3431 USB2.0 Hub, USB 2.10, 4 ports, ppps]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0503 power highspeed enable connect [2109:2822 VIA Labs, Inc. USB2.0 Hub 000000001, USB 2.10, 4 ports, ppps]
  Port 4: 0103 power
Current status for hub 1 [1d6b:0002 Linux 6.6.51-v8+ xhci-hcd xHCI Host Controller 0000:01:00.0, USB 2.00, 1 ports, ppps]
  Port 1: 0503 power highspeed enable connect [2109:3431 USB2.0 Hub, USB 2.10, 4 ports, ppps]

```

**Comment by mvp** [comment]
Note that Inateck HB2025A is listed as having some weird issues e.g. [USB2 only](https://bit.ly/3wXF5UO) compatible, so I am not surprised you have issues with it. Perhaps we should remove it from the list...

If you want relatively cheap and reliable solution specifically for RPi4, I would recommend getting UUGear Mega4.
It was specifically designed to support stacking on top of RPi4, per-port power switching, USB3, and is quite cheap.
