### ISSUE TITLE
Confusing licenses

### ISSUE THREAD

**Issue by skitt** [mvp/uhubctl#6]
Hi,

I came across your project from your answer on http://unix.stackexchange.com/a/321945/86440. I noticed that the license situation is confusing: your README and source headers mention GPLv2, but your LICENSE file is 2-clause BSD. Which license did you intend to use?

Thanks,

Stephen

**Comment by mvp** [comment]
Argh, yes, this is confusing. I intended GPL, which is stated at the top of `uhubctl.c`. I'll change LICENSE file to reflect that.
