### ISSUE TITLE
internal hub, ppps supported?

### ISSUE THREAD

**Issue by roccopietrini** [mvp/uhubctl#61]
Hi,
came here looking for a solution to this problem: 
https://unix.stackexchange.com/questions/414746/reset-usb-port-how-to-obtain-same-effect-of-physical-disconnection-or-poweroff

running uhubctl without any argument i get: No compatible smart hubs detected!

Running lsusb I get: vendor and product 1d6b:0002 which is not very useful. Motherboard is Asus UN45. Any hints? Thank you

**Comment by mvp** [comment]
Try running it with sudo (as root). If that doesn't print anything, your hub must be not compatible.
