### ISSUE TITLE
Hubs confirmed to work with uhubctl

### ISSUE THREAD

**Issue by covex** [mvp/uhubctl#73]
I can confirm the D-Link DUB-H4/D1 - H/W Ver. D1 works with uhubclt.
This is  4 port "smart" hub with external power of 5V/2.5A

lsusb
Bus 001 Device 008: ID 05e3:0608 Genesys Logic, Inc. Hub

Hub is detected like
Feb 24 12:55:01 kernel: usb 8-2: new high-speed USB device number 53 using xhci_hcd
Feb 24 12:55:02 kernel: usb 8-2: New USB device found, idVendor=05e3, idProduct=0608
Feb 24 12:55:02 kernel: usb 8-2: New USB device strings: Mfr=0, Product=1, SerialNumber=0
Feb 24 12:55:02 kernel: usb 8-2: Product: USB2.0 Hub
Feb 24 12:55:02 kernel: hub 8-2:1.0: USB hub found
Feb 24 12:55:02 kernel: hub 8-2:1.0: 4 ports detected

# uhubctl 
Current status for hub 1-3 [05e3:0608 USB2.0 Hub, USB 2.10, 4 ports]
  Port 1: 0103 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
# uhubctl -a off -p 2
Current status for hub 1-3 [05e3:0608 USB2.0 Hub, USB 2.10, 4 ports]
  Port 2: 0100 power
# uhubctl 
Current status for hub 1-3 [05e3:0608 USB2.0 Hub, USB 2.10, 4 ports]
  Port 1: 0103 power
  Port 2: 0000 off
  Port 3: 0100 power
  Port 4: 0100 power

The thing is that if there is any device in the port the -a off causes it to disconnect, but reconnects immediately. It looks it does not stay off. But this is how USB probably should work.

**Comment by mvp** [comment]
Thanks for reporting this, @covex! But we already have this hub in supported list.

Regarding immediate reconnection, this is Linux kernel issue, partially discussed in https://www.spinics.net/lists/linux-usb/msg157418.html.
You should be able to solve it by adding -r 10 to make it turn off few times in quick succession.
