### ISSUE TITLE
Targus Hub not working

### ISSUE THREAD

**Issue by deepakkapoor624** [mvp/uhubctl#76]
I am using 3.0 Targus Hub but on running uhubctl it shows no smart hub found.

**Comment by mvp** [comment]
Targus USB 3.0 hub is not on supported list. You need hub which matches model from the list exactly.

**Comment by mvp** [comment]
Closing. Please provide more information if you think that your hub is on supported list.

**Comment by deepakkapoor624** [comment]
what additional information you need . Please let me know.

**Comment by mvp** [comment]
Just find/buy hub from supported devices list, it should work.

If uhubctl shows no compatible devices detected, your hub isn't compatible. However, on Linux you may need to run it under sudo (or configure udev USB permissions).

**Comment by deepakkapoor624** [comment]
I bought Targus usb3.0 hub which is on the supported list . But it still shows not compatible.
What extra thing you have to look for supported device. Thanks in advance.

**Comment by mvp** [comment]
There is no Targus USB 3.0 hub on the list, what makes you think so?

Please provide output from uhubctl for your hub, so this can be confirmed.

**Comment by deepakkapoor624** [comment]
Targus PAUH212U Hub is mentioned on the supported device list.
I also bought the usb hub of manufacturer Targus with product and vendor Id of 
05e3:0610

**Comment by mvp** [comment]
Correct, Targus PAUH212U is on the list, but it is old USB 2.0 hub, not USB 3.0.

You have to find device from the list with exact match - not many vendors make compatible hubs. And there is no guarantee that even if old Targus hub worked that new one would, or other way around - this is question to vendors why they choose to sell devices not conforming to USB standard.

**Comment by deepakkapoor624** [comment]
Thanks for your response.
