### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by gfa** [mvp/uhubctl#77]
Hello

I'm about to package uhubctl for debian, would you tag a release so we don't ship an snapshot?

thanks

**Comment by mvp** [comment]
Oh, nice! Thanks a lot for doing it! I am about to add some USB 3.0 fixes over this weekend. Can you wait until Monday?

**Comment by gfa** [comment]
Sure! 

On Fri, Mar 09, 2018 at 02:25:14AM +0000, mvp wrote:
>Oh, nice! Thanks a lot for doing it! I am about to add some USB 3.0 fixes over this weekend. Can you wait until Monday?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mvp/uhubctl/issues/77#issuecomment-371692783

-- 
IRC: gfa
GPG: 0X44BB1BA79F6C6333

**Comment by mvp** [comment]
Done in https://github.com/mvp/uhubctl/releases/tag/v2.0.0

**Comment by gfa** [comment]
Cool, thanks

If you use gpg, it would be great if you can start pushing signed git tags

**Comment by mvp** [comment]
Thanks @gfa, I will consider using gpg.
Do you want to merge debian specific changes you did in https://salsa.debian.org/debian/uhubctl/commits/debian/unstable back into uhubctl repo?
I don't know anything about debian release process.
Can I make it easier for further releases?

**Comment by gfa** [comment]
The only change that would make sense to merge back to your repo is 
https://salsa.debian.org/debian/uhubctl/commit/a60928df05461916f6612f9013c9bedadca5d9cb
but after being reworked as it is debian-specific
This change allows to inject uhubctl's version in the build without having the git repo

Other changes are debian packaging, which are better kept on a different repo than upstream software

Regarding what can you do to make things easier for Debian (and other distros too) 
there is a guide https://wiki.debian.org/UpstreamGuide

however, I must say, you made things pretty easy already! :)

**Comment by mvp** [comment]
Note that I have released uhubctl version 2.1.0, can you please update it in Debian? Thanks!

**Comment by mvp** [comment]
Note that I have released uhubctl version 2.2.0, can you please update it in Debian? Thanks!

**Comment by mvp** [comment]
@gfa , can you please update uhubctl in Debian to version 2.2.0? Thanks

**Comment by gfa** [comment]
@mvp i'm working on that

**Comment by mvp** [comment]
@gfa, can you please update uhubctl in Debian to version 2.3.0? Thanks

**Comment by mvp** [comment]
@gfa, can you please update uhubctl in Debian to version 2.4.0? Note that I do not expect new releases in at least 6 months, possibly more. Thanks!

**Comment by gfa** [comment]
Next Debian release is being prepared, while I could package 2.4.0 I think is better to ship 2.3.0 which has been in testing for a while.

As soon as Debian is released, i'll package 2.4.0 and upload it

**Comment by mvp** [comment]
Your call, 2.4.0 has slightly better error reporting and suppors toggle action.

**Comment by mvp** [comment]
Can you release 2.4.0 now, @gfa?

**Comment by gfa** [comment]
uploaded to experimental

On Thu, Apr 01, 2021 at 10:36:41PM -0700, mvp wrote:
>Can you release 2.4.0 now, @gfa?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mvp/uhubctl/issues/77#issuecomment-812329688

-- 
IRC: gfa
GPG: 0x27263FA42553615F904A7EBE2A40A2ECB8DAD8D5
OLD GPG: 0x44BB1BA79F6C6333

**Comment by mvp** [comment]
@gfa, can you please update uhubctl in Debian to next version 2.6.0? Release notes are [here](https://github.com/mvp/uhubctl/releases/tag/v2.6.0). Thanks!

**Comment by mvp** [comment]
Ping @gfa, can you please release uhubctl 2.6.0 to Debian?
