### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by pgghub** [mvp/uhubctl#79]
Hello,

I noticed the TBD on windows support, but I wanted to submit an issue to keep track of any updates related to windows support. 

Thank you.

Paul

**Comment by mvp** [comment]
@Manel3 started separate project to fix this https://github.com/manel3/usbpower.
I'll assign this to you, @Manel3.

**Comment by mvp** [comment]
We haven't seen anything promising for Windows support for 1.5 years now :-(
I will close it for now as won't fix. Let's reopen it when Windows will be running on Linux kernel :-)
