### ISSUE TITLE
Raspi Model B

### ISSUE THREAD

**Issue by gruessung** [mvp/uhubctl#85]
I have trouble to turn off a specific usb port on my raspi model b.
I see that port 1 is usb ethernet.
So port 2 or 3 have to be my LED stripe.
But 
`sudo ./uhubctl  -a off -p 2`
and
`sudo ./uhubctl  -a off -p 3`
didn't work.

Do you have any suggestions?

**Comment by mvp** [comment]
Raspberry Pi Model B hardware does not support power switching. You need model B+, 2 B, or 3 B. If you get compatible model, use port 2 to control all ports 2-5. Port 1 controls Ethernet+wifi.

**Comment by gtzigk** [comment]
Hello, 
is it possible on Pi 3 Model B to control just one Port from 2-5 separately from others and not all of them?
![image](https://user-images.githubusercontent.com/6031196/52901051-b33fb480-3206-11e9-9d4c-4d0091551f87.png)
Unfortunately I guess not...

Thanks

**Comment by mvp** [comment]
Check https://github.com/mvp/uhubctl/issues/138.

**Comment by gtzigk** [comment]
Thanks for the response!
