### ISSUE TITLE
DUB-H4 rev C1 (black) NOT working

### ISSUE THREAD

**Issue by bilbolodz** [mvp/uhubctl#88]
It looks that DUB-H4 H/W ver C1 (black) 2101:8500 Action Star USB2.0 Hub, USB 2.00, 5 ports

is NOT working (uhubctl doesn't recognize it as "smart hub capable").

**Comment by mvp** [comment]
Correct, but it is not listed in table only rev D1 is mentioned.

**Comment by bilbolodz** [comment]
I know. I'm not complaining maybe it's worth to mention that there are (at least) two versions of "black edition" and C1 is NOT working.

**Comment by mvp** [comment]
Closing, as only working hardware revisions are listed in supported table.
Rev D is listed and works, rev C isn't.
