### ISSUE TITLE
Moxa Uport-407 hub

### ISSUE THREAD

**Issue by tc-pee** [mvp/uhubctl#92]
Working with raspberry Pi 3 B+
Current status for hub 1-1 [0424:2514, USB 2.00, 4 ports]
  Port 1: 0503 power highspeed enable connect [0424:2514, USB 2.00, 3 ports]
  Port 2: 0503 power highspeed enable connect [110a:0407, USB 2.00, 7 ports]
  Port 3: 0100 power
  Port 4: 0100 power
(Moxa U-407)
Current status for hub 1-1.2 [110a:0407, USB 2.00, 7 ports]
  Port 1: 0503 power highspeed enable connect [0b05:17d2 Realtek 802.11n NIC 123456]
  Port 2: 0503 power highspeed enable connect [0b05:17d2 Realtek 123456]
  Port 3: 0503 power highspeed enable connect [0b05:17d2 Realtek 802.11n NIC 123456]
  Port 4: 0503 power highspeed enable connect [0b05:17d2 Realtek 802.11n NIC]
  Port 5: 0503 power highspeed enable connect [0b05:17d2 Realtek 802.11n NIC 123456]
  Port 6: 0503 power highspeed enable connect [0b05:17d2 Realtek 802.11n NIC 123456]
  Port 7: 0503 power highspeed enable connect [0b05:17d2 Realtek 802.11n NIC 123456]

Also working on Intel NUC PC
Current status for hub 1-1 [8087:8000, USB 2.00, 8 ports]
  Port 1: 0100 power
  Port 2: 0100 power
  Port 3: 0100 power
  Port 4: 0100 power
  Port 5: 0100 power
  Port 6: 0100 power
  Port 7: 0100 power
  Port 8: 0100 power
(Moxa hub)
Current status for hub 2-1 [110a:0407, USB 2.00, 7 ports]
  Port 1: 0503 power highspeed enable connect [0b05:17d2 Realtek 802.11n NIC 123456]
  Port 2: 0503 power highspeed enable connect [0b05:17d2 Realtek 802.11n NIC 123456]
  Port 3: 0503 power highspeed enable connect [0b05:17d2 Realtek 802.11n NIC 123456]
  Port 4: 0503 power highspeed enable connect [0b05:17d2 Realtek 802.11n NIC 123456]
  Port 5: 0100 power
  Port 6: 0100 power
  Port 7: 0100 power

**Comment by mvp** [comment]
Thanks for the report - I will add Moxa uport 407 to compatibility list.

Question about Intel NUC: onboard Intel USB hub seems to support PPPS. Can you please try if uhubctl power switching works on it? Thanks!

**Comment by mvp** [comment]
Added in 4661d892bfac.
