### ISSUE TITLE
AmazonBasics USB3 hub

### ISSUE THREAD

**Issue by jensolsson** [mvp/uhubctl#95]
I have three 7-port AmazonBasics USB3 hubs that I bought for using with uhubctl. I cannot determine if they work or not though.

The devices certainly disconnect from the computer, but the question is if they still charge.
My current theory is that iphones stop charging while android devices continue to charge. Could it be that iPhones automatically stop charging at the same time the data connection is dropped?

**Comment by mvp** [comment]
I think the only reasonable test would be using some really dumb device like USB fan or light to see if it stops spinning or shining.

Or, better yet, use voltmeter on USB wire to see if VBUS is gone...

**Comment by jensolsson** [comment]
I just bought something called a usb multimeter that meassures ampere and voltage. Turned out I was using an incorrect switch. Everything works now!

Kind regards
Jens

Skickat från min iPhone

**Comment by mvp** [comment]
Ah, that's awesome! At last, we have final confirmation that it actually turns off - thank you! I will close this issue then.
